// SPDX-License-Identifier: MIT
// Purpose: render the system-prompt block (PROMPT.md) that lists every
// installed superpowers skill. This block is also what InjectAGENTS
// appends to the user's AGENTS.md, so the agent always sees the current
// set of skills without needing to call MCP at boot.
// Docs: superpowers.doc.md
package superpowers

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// WritePrompt renders the system-prompt block for the given skills and
// writes it to PROMPTFile(). Returns the rendered text. The block is
// wrapped in the same HTML-comment sentinels that InjectAGENTS uses, so
// it can be round-tripped through AGENTS.md without re-rendering.
func WritePrompt(skills []SkillInfo) (string, error) {
	body := RenderPrompt(skills)
	return body, os.WriteFile(PROMPTFile(), []byte(body), 0o644)
}

// RenderPrompt produces the full PROMPT.md content. It is exported so
// callers (e.g. tests, custom dashboards) can preview the block without
// touching the filesystem.
func RenderPrompt(skills []SkillInfo) string {
	pin, _ := CurrentPin()
	var b strings.Builder
	b.WriteString("# SIN-Code superpowers — system prompt\n\n")
	b.WriteString("Auto-generated by `sin-code superpowers install`.\n")
	b.WriteString("Do not edit by hand; re-run `sin-code superpowers install` to refresh.\n\n")
	if pin != nil {
		fmt.Fprintf(&b, "**Pinned commit:** `%s` (branch `%s`, updated %s)\n\n",
			pin.SHA, pin.Branch, pin.UpdatedAt.Format(time.RFC3339))
	} else {
		b.WriteString("**Pinned commit:** _not installed_ — run `sin-code superpowers install`.\n\n")
	}
	if len(skills) == 0 {
		b.WriteString("_No skills discovered in_ `" + SkillsDir() + "`.\n")
		return b.String()
	}
	fmt.Fprintf(&b, "**Skills available (%d):**\n\n", len(skills))
	for _, s := range skills {
		name := s.Name
		if name == "" {
			name = filepath.Base(filepath.Dir(s.Path))
		}
		desc := s.Description
		if desc == "" {
			desc = "(no description in frontmatter)"
		}
		// Bullet form. Each line is a full sentence so the agent can
		// decide "yes, this skill applies" without re-parsing the file.
		fmt.Fprintf(&b, "- **%s** — %s\n", name, desc)
		fmt.Fprintf(&b, "  - path: `%s`\n", s.Path)
		fmt.Fprintf(&b, "  - sha256: `%s`\n", s.Hash)
	}
	b.WriteString("\n## How to use a skill\n\n")
	b.WriteString("1. Read the SKILL.md at the path above (it is the full text — no\n")
	b.WriteString("   truncation, no summary).\n")
	b.WriteString("2. Follow its instructions literally. If it asks you to read another\n")
	b.WriteString("   file, use `sin-code read` (hashline-anchored, syntax-validated).\n")
	b.WriteString("3. When you finish, run the verification step it specifies. If the\n")
	b.WriteString("   skill mentions a PoC or Oracle check, prefer those over manual\n")
	b.WriteString("   eyeballing — the SIN-Code mandate M3 (verification-first) is in\n")
	b.WriteString("   effect for superpowers skills too.\n")
	return b.String()
}

// AGENTSSnippet returns just the markdown body suitable for embedding in
// AGENTS.md (no top-level heading, no file path breadcrumb).
func AGENTSSnippet(skills []SkillInfo) string {
	pin, _ := CurrentPin()
	var b strings.Builder
	b.WriteString("## Superpowers (obra/superpowers, via SIN-Code)\n\n")
	if pin != nil {
		fmt.Fprintf(&b, "Pinned at `%s` (branch `%s`). ", pin.SHA, pin.Branch)
	} else {
		b.WriteString("_Not installed._ ")
	}
	// NOTE: explicit `+` between adjacent string literals is required by
	// Go's grammar in call-argument position (the lexical "string concat"
	// rule only applies to top-level composite literals / const decls).
	hint := "%d skill(s) available. Use `sin-code superpowers find <query>` " +
		"to search or `sin-code superpowers show <name>` to load the full SKILL.md.\n\n"
	fmt.Fprintf(&b, hint, len(skills))
	for _, s := range skills {
		name := s.Name
		if name == "" {
			name = filepath.Base(filepath.Dir(s.Path))
		}
		desc := s.Description
		if desc == "" {
			desc = "(no description)"
		}
		fmt.Fprintf(&b, "- **%s** — %s\n", name, desc)
	}
	return b.String()
}
