// SPDX-License-Identifier: MIT
// Purpose: undercover mode tests (issue #274).
package commands

import (
	"context"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/session"
)

func newUndercoverSession(t *testing.T) *session.Session {
	t.Helper()
	store, err := session.Open(filepath.Join(t.TempDir(), "uc.db"))
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { store.Close() })
	sess, err := store.StartOrResume("")
	if err != nil {
		t.Fatalf("start session: %v", err)
	}
	return sess
}

func TestUndercoverMode_EnableDisableToggle(t *testing.T) {
	u := NewUndercoverMode()
	if u.Enabled() {
		t.Fatal("default should be disabled")
	}
	u.Enable()
	if !u.Enabled() {
		t.Error("Enable failed")
	}
	u.Disable()
	if u.Enabled() {
		t.Error("Disable failed")
	}
	if got := u.Toggle(); !got {
		t.Error("Toggle from disabled should return true (new state on)")
	}
	if !u.Enabled() {
		t.Error("Toggle failed to enable")
	}
	if got := u.Toggle(); got {
		t.Error("Toggle from enabled should return false (new state off)")
	}
	if u.Enabled() {
		t.Error("Toggle failed to disable")
	}
}

func TestUndercoverMode_SetEnabled(t *testing.T) {
	u := NewUndercoverMode()
	u.SetEnabled(true)
	if !u.Enabled() {
		t.Error("SetEnabled(true) failed")
	}
	u.SetEnabled(false)
	if u.Enabled() {
		t.Error("SetEnabled(false) failed")
	}
}

func TestUndercoverFilter_RemovesCoAuthoredByAI(t *testing.T) {
	u := NewUndercoverMode()
	msg := "Fix auth bug\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "Co-Authored-By") {
		t.Errorf("Co-Authored-By not removed: %q", out)
	}
	if !strings.Contains(out, "Fix auth bug") {
		t.Errorf("message body lost: %q", out)
	}
}

func TestUndercoverFilter_RemovesCoAuthoredBySIN(t *testing.T) {
	u := NewUndercoverMode()
	msg := "feat: add endpoint\n\nCo-Authored-By: SIN-Code <bot@sin-code.dev>\n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "Co-Authored-By") {
		t.Errorf("Co-Authored-By SIN not removed: %q", out)
	}
	if !strings.Contains(out, "feat: add endpoint") {
		t.Errorf("message body lost: %q", out)
	}
}

func TestUndercoverFilter_RemovesGeneratedBy(t *testing.T) {
	u := NewUndercoverMode()
	msg := "Refactor module\n\nGenerated by SIN-Code\nGenerated by AI\n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "Generated by") {
		t.Errorf("Generated by not removed: %q", out)
	}
	if !strings.Contains(out, "Refactor module") {
		t.Errorf("message body lost: %q", out)
	}
}

func TestUndercoverFilter_RemovesEmojiMarkers(t *testing.T) {
	u := NewUndercoverMode()
	msg := "Update docs 🤖\n\nAI-generated\n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "🤖") {
		t.Errorf("emoji not removed: %q", out)
	}
	if strings.Contains(out, "AI-generated") {
		t.Errorf("AI-generated not removed: %q", out)
	}
	if !strings.Contains(out, "Update docs") {
		t.Errorf("message body lost: %q", out)
	}
}

func TestUndercoverFilter_PreservesNormalMessage(t *testing.T) {
	u := NewUndercoverMode()
	msg := "fix: handle nil pointer in parser\n\nThe parser crashed when input was empty."
	out := u.FilterCommitMessage(msg)
	if out != msg {
		t.Errorf("normal message should be preserved, got %q", out)
	}
}

func TestUndercoverFilter_HandlesMultipleAITrailers(t *testing.T) {
	u := NewUndercoverMode()
	msg := "feat: big change\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-Authored-By: AI <ai@bot.com>\nGenerated by SIN-Code\n🤖\n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "Co-Authored-By") {
		t.Errorf("Co-Authored-By not removed: %q", out)
	}
	if strings.Contains(out, "Generated by") {
		t.Errorf("Generated by not removed: %q", out)
	}
	if strings.Contains(out, "🤖") {
		t.Errorf("emoji not removed: %q", out)
	}
	if !strings.Contains(out, "feat: big change") {
		t.Errorf("message body lost: %q", out)
	}
}

func TestUndercoverFilter_EmptyMessage(t *testing.T) {
	u := NewUndercoverMode()
	if out := u.FilterCommitMessage(""); out != "" {
		t.Errorf("empty message should return empty, got %q", out)
	}
}

func TestUndercoverFilter_TrimsTrailingWhitespace(t *testing.T) {
	u := NewUndercoverMode()
	msg := "fix: thing   \n\nCo-Authored-By: AI <a@b.c>\n  \n"
	out := u.FilterCommitMessage(msg)
	if strings.Contains(out, "   ") {
		t.Errorf("trailing whitespace not trimmed: %q", out)
	}
	for _, ln := range strings.Split(out, "\n") {
		if ln != strings.TrimRight(ln, " \t") {
			t.Errorf("line has trailing whitespace: %q", ln)
		}
	}
}

func TestUndercoverGitIdentity_ReturnsUserConfig(t *testing.T) {
	old := gitConfigFn
	defer func() { gitConfigFn = old }()
	gitConfigFn = func(key string) (string, error) {
		switch key {
		case "user.name":
			return "Jeremy Schulze", nil
		case "user.email":
			return "jeremy@example.com", nil
		default:
			return "", nil
		}
	}
	u := NewUndercoverMode()
	name, email := u.GitIdentity()
	if name != "Jeremy Schulze" {
		t.Errorf("name: %q", name)
	}
	if email != "jeremy@example.com" {
		t.Errorf("email: %q", email)
	}
}

func TestUndercoverGitIdentity_EmptyWhenUnset(t *testing.T) {
	old := gitConfigFn
	defer func() { gitConfigFn = old }()
	gitConfigFn = func(key string) (string, error) {
		return "", nil
	}
	u := NewUndercoverMode()
	name, email := u.GitIdentity()
	if name != "" || email != "" {
		t.Errorf("expected empty identity, got name=%q email=%q", name, email)
	}
}

func TestUndercoverCommand_ToggleOnOff(t *testing.T) {
	mode := NewUndercoverMode()
	cmd := NewUndercoverCommand(mode)
	sess := newUndercoverSession(t)

	out, err := cmd.Execute(context.Background(), "on", sess)
	if err != nil {
		t.Fatalf("on: %v", err)
	}
	if !strings.Contains(out, "ON") {
		t.Errorf("on output: %q", out)
	}
	if !mode.Enabled() {
		t.Error("mode should be enabled after 'on'")
	}

	out, err = cmd.Execute(context.Background(), "off", sess)
	if err != nil {
		t.Fatalf("off: %v", err)
	}
	if !strings.Contains(out, "OFF") {
		t.Errorf("off output: %q", out)
	}
	if mode.Enabled() {
		t.Error("mode should be disabled after 'off'")
	}

	out, err = cmd.Execute(context.Background(), "", sess)
	if err != nil {
		t.Fatalf("toggle: %v", err)
	}
	if !strings.Contains(out, "ON") {
		t.Errorf("toggle output: %q", out)
	}
	if !mode.Enabled() {
		t.Error("mode should be enabled after bare toggle")
	}
}

func TestUndercoverCommand_StatusAndUsage(t *testing.T) {
	mode := NewUndercoverMode()
	cmd := NewUndercoverCommand(mode)
	sess := newUndercoverSession(t)

	out, err := cmd.Execute(context.Background(), "status", sess)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if !strings.Contains(out, "OFF") {
		t.Errorf("status off: %q", out)
	}

	mode.Enable()
	out, err = cmd.Execute(context.Background(), "status", sess)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if !strings.Contains(out, "ON") {
		t.Errorf("status on: %q", out)
	}

	out, err = cmd.Execute(context.Background(), "garbage", sess)
	if err != nil {
		t.Fatalf("bad arg: %v", err)
	}
	if !strings.Contains(out, "usage:") {
		t.Errorf("usage hint for bad arg: %q", out)
	}
}

func TestUndercoverCommand_NameAndDescription(t *testing.T) {
	cmd := NewUndercoverCommand(NewUndercoverMode())
	if cmd.Name() != "undercover" {
		t.Errorf("Name: %q", cmd.Name())
	}
	if cmd.Description() == "" {
		t.Error("empty description")
	}
}

func TestUndercoverCommand_NilModeSafe(t *testing.T) {
	cmd := NewUndercoverCommand(nil)
	if cmd.Mode() == nil {
		t.Fatal("nil mode should be replaced with a fresh one")
	}
	out, err := cmd.Execute(context.Background(), "on", newUndercoverSession(t))
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !cmd.Mode().Enabled() {
		t.Error("mode should be enabled")
	}
	if !strings.Contains(out, "ON") {
		t.Errorf("out: %q", out)
	}
}

func TestUndercoverMode_ConcurrentToggle(t *testing.T) {
	u := NewUndercoverMode()
	var wg sync.WaitGroup
	onCount := atomic.Int64{}
	const n = 100
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if u.Toggle() {
				onCount.Add(1)
			}
		}()
	}
	wg.Wait()
	final := u.Enabled()
	sum := onCount.Load()
	if final && sum%2 == 0 {
		t.Errorf("final=on but even number of toggles returned true: %d", sum)
	}
	if !final && sum%2 != 0 {
		t.Errorf("final=off but odd number of toggles returned true: %d", sum)
	}
}

func TestUndercoverMode_NilSafe(t *testing.T) {
	var u *UndercoverMode
	if u.Enabled() {
		t.Error("nil mode should report disabled")
	}
}

func TestUndercoverConfigKey(t *testing.T) {
	if ConfigKeyUndercover != "git.undercover" {
		t.Errorf("config key: %q", ConfigKeyUndercover)
	}
}

func TestRegistry_RegisterAndGet(t *testing.T) {
	r := NewRegistry()
	btw := NewBTWCommand(nil, "")
	uc := NewUndercoverCommand(NewUndercoverMode())
	r.Register(btw)
	r.Register(uc)
	if got, ok := r.Get("btw"); !ok || got != btw {
		t.Error("Get btw failed")
	}
	if got, ok := r.Get("undercover"); !ok || got != uc {
		t.Error("Get undercover failed")
	}
	if _, ok := r.Get("nope"); ok {
		t.Error("unknown command should not be found")
	}
	names := r.Names()
	if len(names) != 2 {
		t.Errorf("Names: %v", names)
	}
}

func TestRegistry_Dispatch(t *testing.T) {
	r := NewRegistry()
	r.Register(NewUndercoverCommand(NewUndercoverMode()))
	sess := newUndercoverSession(t)
	handled, out, err := r.Dispatch(context.Background(), "/undercover on", sess)
	if !handled {
		t.Error("should be handled")
	}
	if err != nil {
		t.Errorf("err: %v", err)
	}
	if !strings.Contains(out, "ON") {
		t.Errorf("out: %q", out)
	}
	handled, _, _ = r.Dispatch(context.Background(), "not a slash", sess)
	if handled {
		t.Error("non-slash line should not be handled")
	}
	handled, _, _ = r.Dispatch(context.Background(), "/unknown", sess)
	if handled {
		t.Error("unknown slash should not be handled by this registry")
	}
}

func TestRegistry_NilSafe(t *testing.T) {
	var r *Registry
	if _, ok := r.Get("x"); ok {
		t.Error("nil registry Get should return false")
	}
	if names := r.Names(); names != nil {
		t.Errorf("nil registry Names: %v", names)
	}
	handled, _, _ := r.Dispatch(context.Background(), "/x", nil)
	if handled {
		t.Error("nil registry should not handle")
	}
}

func TestRegistry_RegisterNilPanics(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("Register(nil) should panic")
		}
	}()
	NewRegistry().Register(nil)
}
