// SPDX-License-Identifier: MIT
// Purpose: Undercover mode (issue #274) — when enabled, git commits made by
// SIN-Code do NOT reveal AI involvement. No "Co-Authored-By: AI" trailers,
// no "Generated by" lines, no emoji markers. The user's real git config
// identity is used instead of any AI identity. Modeled on Claude Code's
// leaked src/git/undercover.ts. The mode is session-isolated state held in
// UndercoverMode; the /undercover slash command toggles it.
package commands

import (
	"context"
	"os/exec"
	"regexp"
	"strings"
	"sync/atomic"

	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/session"
)

// ConfigKeyUndercover is the TOML config key that seeds the initial
// undercover state (bool, default false). The chat layer reads this and
// calls SetEnabled at startup.
const ConfigKeyUndercover = "git.undercover"

// gitConfigFn is the test seam for `git config <key>` lookups. Production
// runs the real git binary; tests swap in a stub to avoid shelling out.
var gitConfigFn = func(key string) (string, error) {
	out, err := exec.Command("git", "config", "--get", key).Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// coAuthoredAI matches Co-Authored-By trailers that reference an AI agent
// (Claude, Anthropic, SIN-Code, any name containing AI/SIN/Claude).
var coAuthoredAI = regexp.MustCompile(`(?mi)^Co-Authored-By:.*(\bAI\b|\bClaude\b|\bsin\b|anthropic|noreply@anthropic\.com).*\r?\n?`)

// generatedBy matches "Generated by SIN-Code", "Generated by AI", or any
// "Generated by <agent>" line.
var generatedBy = regexp.MustCompile(`(?mi)^Generated by\b.*\r?\n?`)

// aiMarkers matches standalone emoji / text markers that flag AI authorship.
var aiMarkers = regexp.MustCompile(`(?m)(🤖|AI-generated)\r?\n?`)

// UndercoverMode manages the session-local undercover flag and provides
// commit-message filtering + git-identity resolution. It is safe for
// concurrent use (mandate M7): the flag is stored in an atomic.Bool and
// every toggle uses a CompareAndSwap loop.
type UndercoverMode struct {
	enabled atomic.Bool
}

// NewUndercoverMode returns a mode disabled by default.
func NewUndercoverMode() *UndercoverMode {
	return &UndercoverMode{}
}

// Enabled reports whether undercover mode is active.
func (u *UndercoverMode) Enabled() bool {
	if u == nil {
		return false
	}
	return u.enabled.Load()
}

// Enable turns undercover mode on.
func (u *UndercoverMode) Enable() {
	u.enabled.Store(true)
}

// Disable turns undercover mode off.
func (u *UndercoverMode) Disable() {
	u.enabled.Store(false)
}

// SetEnabled sets the flag to the given value (used by the config loader at
// startup to honour git.undercover).
func (u *UndercoverMode) SetEnabled(b bool) {
	u.enabled.Store(b)
}

// Toggle flips the flag atomically and returns the new state. Race-free via
// a CompareAndSwap loop (mandate M7).
func (u *UndercoverMode) Toggle() bool {
	for {
		old := u.enabled.Load()
		if u.enabled.CompareAndSwap(old, !old) {
			return !old
		}
	}
}

// FilterCommitMessage removes AI-revealing trailers and markers from a
// commit message. It strips:
//   - Co-Authored-By lines mentioning AI / Claude / sin / anthropic
//   - "Generated by ..." lines
//   - 🤖 emoji and "AI-generated" markers
// Trailing whitespace is removed from every surviving line and any blank
// tail is trimmed. A non-enabled mode still filters (the filter is
// idempotent and safe to call unconditionally), matching the issue's
// requirement that the /undercover command surface the cleaned message.
func (u *UndercoverMode) FilterCommitMessage(msg string) string {
	if msg == "" {
		return ""
	}
	s := coAuthoredAI.ReplaceAllString(msg, "")
	s = generatedBy.ReplaceAllString(s, "")
	s = aiMarkers.ReplaceAllString(s, "")
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		lines[i] = strings.TrimRight(ln, " \t\r")
	}
	out := strings.Join(lines, "\n")
	return strings.TrimRight(out, "\n")
}

// GitIdentity returns the user's real git config user.name and user.email.
// When git is unavailable or a value is unset, the corresponding return is
// empty (no error) — callers fall back to environment defaults.
func (u *UndercoverMode) GitIdentity() (name, email string) {
	name, _ = gitConfigFn("user.name")
	email, _ = gitConfigFn("user.email")
	return name, email
}

// UndercoverCommand wraps an UndercoverMode as a built-in slash command.
//   /undercover          → toggle
//   /undercover on       → enable
//   /undercover off      → disable
//   /undercover status   → report current state
type UndercoverCommand struct {
	mode *UndercoverMode
}

// NewUndercoverCommand constructs the /undercover command bound to the
// given mode. The mode is shared so toggles persist across the session.
func NewUndercoverCommand(mode *UndercoverMode) *UndercoverCommand {
	if mode == nil {
		mode = NewUndercoverMode()
	}
	return &UndercoverCommand{mode: mode}
}

// Name returns "undercover".
func (c *UndercoverCommand) Name() string { return "undercover" }

// Description returns the one-line help text.
func (c *UndercoverCommand) Description() string {
	return "Toggle undercover mode (hide AI identity in commits)"
}

// Execute handles /undercover [on|off|status]. The session argument is
// accepted for interface compliance but not modified.
func (c *UndercoverCommand) Execute(ctx context.Context, args string, sess *session.Session) (string, error) {
	_ = ctx
	switch strings.ToLower(strings.TrimSpace(args)) {
	case "", "toggle":
		on := c.mode.Toggle()
		return formatUndercoverStatus(on), nil
	case "on", "enable", "true":
		c.mode.Enable()
		return formatUndercoverStatus(true), nil
	case "off", "disable", "false":
		c.mode.Disable()
		return formatUndercoverStatus(false), nil
	case "status", "show":
		return formatUndercoverStatus(c.mode.Enabled()), nil
	default:
		return "usage: /undercover [on|off|status] — toggle undercover mode", nil
	}
}

// Mode exposes the underlying UndercoverMode so the chat layer can query
// Enabled() before committing and call FilterCommitMessage on the message.
func (c *UndercoverCommand) Mode() *UndercoverMode { return c.mode }

func formatUndercoverStatus(on bool) string {
	if on {
		return "undercover mode: ON — AI identity hidden in commits"
	}
	return "undercover mode: OFF — AI identity visible in commits"
}

// FilterCommitMessage is a convenience that delegates to the wrapped mode.
func (c *UndercoverCommand) FilterCommitMessage(msg string) string {
	return c.mode.FilterCommitMessage(msg)
}
