// SPDX-License-Identifier: MIT
// Purpose: Persistent TUI preferences — read/write ~/.config/sin/tui.toml.
// Hand-rolled TOML scalar parser; no new dependencies.
// Docs: config.doc.md

package tui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/OpenSIN-Code/SIN-Code/internal/tui/theme"
)

// ConfigDir is the directory under $HOME holding TUI config. Kept consistent
// with `sin config` so users can locate it without a flag.
const ConfigDir = ".config/sin"

// ConfigFileName is the TOML file name within ConfigDir.
const ConfigFileName = "tui.toml"

// Config holds persisted TUI preferences. Add fields here as they become
// persistent (window split %, last opened command, etc.).
type Config struct {
	// Theme is "dark" (default) or "light". Other values are rejected
	// on load to keep us forward-compatible with future palettes.
	Theme string
}

// DefaultConfig returns the baseline preferences used when no config file
// is present or it cannot be read.
func DefaultConfig() Config {
	return Config{Theme: theme.ThemeDark}
}

// ConfigPath returns the absolute path to the TUI config file. Exported so
// tests and `sin config` can locate it.
func ConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ConfigDir, ConfigFileName), nil
}

// LoadConfig reads the config file. Missing file, parse error, or invalid
// values all degrade silently to DefaultConfig — a corrupt config must
// never wedge the TUI on launch.
func LoadConfig() Config {
	cfg := DefaultConfig()
	path, err := ConfigPath()
	if err != nil {
		return cfg
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg
	}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := splitKV(line)
		if !ok {
			continue
		}
		switch key {
		case "theme":
			if val == theme.ThemeDark || val == theme.ThemeLight {
				cfg.Theme = val
			}
		}
	}
	return cfg
}

// SaveConfig writes the config file, creating the parent dir if needed.
// File mode is 0o644 — config is non-secret and the user may want to read
// it with `cat`.
func SaveConfig(cfg Config) error {
	path, err := ConfigPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(
		"# Auto-generated by sin tui. Hand-edits are preserved on the next save.\ntheme = %q\n",
		cfg.Theme,
	)
	return os.WriteFile(path, []byte(body), 0o644)
}

// splitKV parses a single `key = "value"` TOML line. Returns key, value,
// and false if the line is not a plain scalar assignment. Pulled out for
// readability and so we can swap in a real TOML parser later without
// touching LoadConfig.
func splitKV(line string) (string, string, bool) {
	eq := strings.Index(line, "=")
	if eq < 0 {
		return "", "", false
	}
	key := strings.TrimSpace(line[:eq])
	if key == "" {
		return "", "", false
	}
	val := strings.TrimSpace(line[eq+1:])
	// Strip a single pair of matching quotes — tolerate both " and '.
	if len(val) >= 2 {
		first, last := val[0], val[len(val)-1]
		if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
			val = val[1 : len(val)-1]
		}
	}
	return key, val, true
}
