// SPDX-License-Identifier: MIT
package main

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/agentloop"
	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/autonomy"
)

func autoCreatePR(ctx context.Context, goal *autonomy.Goal, res *agentloop.Result) error {
	if goal == nil {
		return fmt.Errorf("autoCreatePR: nil goal, nothing to PR")
	}
	if res == nil {
		return fmt.Errorf("autoCreatePR: nil result, nothing to PR")
	}
	branch := fmt.Sprintf("goal-%d", goal.ID)
	// TOCTOU: the diff is checked before branch creation; the working tree
	// may change between this check and the commit. We accept the race —
	// the daemon is single-threaded per workspace in practice.
	diffOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "diff", "--stat", "HEAD").CombinedOutput()
	if err != nil || strings.TrimSpace(string(diffOut)) == "" {
		fmt.Printf("daemon: goal %d no changes\n", goal.ID)
		return nil
	}

	origBranchOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "rev-parse", "--abbrev-ref", "HEAD").CombinedOutput()
	if err != nil {
		return fmt.Errorf("git rev-parse --abbrev-ref HEAD: %v: %s", err, string(origBranchOut))
	}
	origBranch := strings.TrimSpace(string(origBranchOut))

	// Delete existing branch if it exists, then create fresh from main.
	// This avoids stale/uncommitted changes from previous runs.
	// Check if branch exists first to avoid error from "git branch -D" on non-existent branch.
	if err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "rev-parse", "--verify", branch).Run(); err == nil {
		if delOut, delErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "branch", "-D", branch).CombinedOutput(); delErr != nil {
			fmt.Printf("daemon: goal %d warning: could not delete branch %s: %v: %s\n", goal.ID, branch, delErr, string(delOut))
		}
	}
	if cbOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", "-b", branch, "main").CombinedOutput(); err != nil {
		return fmt.Errorf("git checkout -b %s main: %v: %s", branch, err, string(cbOut))
	}

	statusOut, _ := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "status", "--porcelain").CombinedOutput()
	if strings.TrimSpace(string(statusOut)) != "" {
		if addOut, addErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "add", "-A").CombinedOutput(); addErr != nil {
			if coOut, coErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).CombinedOutput(); coErr != nil {
				fmt.Printf("daemon: goal %d warning: could not restore branch %s: %v: %s\n", goal.ID, origBranch, coErr, string(coOut))
			}
			return fmt.Errorf("git add -A: %v: %s", addErr, string(addOut))
		}
		commitMsg := fmt.Sprintf("feat: resolve goal %d\n\nGenerated by sin-code daemon (autodev).\nCo-authored-by: sin-code-daemon <daemon@sin-code.local>", goal.ID)
		if commitOut, commitErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "commit", "-m", commitMsg).CombinedOutput(); commitErr != nil {
			if coOut, coErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).CombinedOutput(); coErr != nil {
				fmt.Printf("daemon: goal %d warning: could not restore branch %s: %v: %s\n", goal.ID, origBranch, coErr, string(coOut))
			}
			return fmt.Errorf("git commit: %v: %s", commitErr, string(commitOut))
		}
	}

	title := fmt.Sprintf("[Autodev] Goal #%d: %s", goal.ID, autodevTruncate(goal.Prompt, 60))
	body := fmt.Sprintf("## Automated PR\n**Goal:** %d\n**Verified:** %v\n**Turns:** %d\n\n%s", goal.ID, res.Verified, res.Turns, res.Summary)

	baseRepo := ""

	upstreamURLOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "remote", "get-url", "upstream").CombinedOutput()
	if err != nil || strings.TrimSpace(string(upstreamURLOut)) == "" {
		fmt.Printf("daemon: goal %d warning: upstream remote not found or empty, trying origin\n", goal.ID)
		originURLOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "remote", "get-url", "origin").CombinedOutput()
		if err != nil || strings.TrimSpace(string(originURLOut)) == "" {
			fmt.Printf("daemon: goal %d warning: origin remote not found or empty, PR will be created without --repo flag (may fail in fork workflows)\n", goal.ID)
		} else {
			upstreamURLOut = originURLOut
		}
	}

	if upstreamURL := strings.TrimSpace(string(upstreamURLOut)); upstreamURL != "" {
		if strings.HasPrefix(upstreamURL, "git@github.com:") {
			baseRepo = strings.TrimSuffix(strings.TrimPrefix(upstreamURL, "git@github.com:"), ".git")
		} else if strings.HasPrefix(upstreamURL, "https://github.com/") {
			baseRepo = strings.TrimSuffix(strings.TrimPrefix(upstreamURL, "https://github.com/"), ".git")
		} else {
			fmt.Printf("daemon: goal %d warning: remote URL is not a GitHub URL (%s), PR will be created without --repo flag\n", goal.ID, upstreamURL)
		}
	}

	args := []string{"pr", "create", "--title", title, "--body", body, "--head", branch, "--base", "main"}
	if baseRepo != "" {
		args = append(args, "--repo", baseRepo)
	}
	prOut, err := exec.CommandContext(ctx, "gh", args...).CombinedOutput()
	if err != nil {
		if coOut, coErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).CombinedOutput(); coErr != nil {
			fmt.Printf("daemon: goal %d warning: could not restore branch %s: %v: %s\n", goal.ID, origBranch, coErr, string(coOut))
		}
		return fmt.Errorf("gh pr create: %v: %s", err, string(prOut))
	}
	fmt.Printf("daemon: goal %d PR created: %s\n", goal.ID, strings.TrimSpace(string(prOut)))

	if coOut, coErr := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).CombinedOutput(); coErr != nil {
		fmt.Printf("daemon: goal %d warning: could not restore branch %s: %v: %s\n", goal.ID, origBranch, coErr, string(coOut))
	}
	return nil
}

func autodevTruncate(s string, maxLen int) string {
	if maxLen < 3 {
		return s
	}
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
