// SPDX-License-Identifier: MIT
package main

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/agentloop"
	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/autonomy"
)

func autoCreatePR(ctx context.Context, goal *autonomy.Goal, res *agentloop.Result) error {
	if goal == nil {
		return fmt.Errorf("autoCreatePR: nil goal, nothing to PR")
	}
	if res == nil {
		return fmt.Errorf("autoCreatePR: nil result, nothing to PR")
	}
	branch := fmt.Sprintf("goal-%d", goal.ID)
	diffOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "diff", "--stat", "HEAD").CombinedOutput()
	if err != nil || strings.TrimSpace(string(diffOut)) == "" {
		fmt.Printf("daemon: goal %d no changes\n", goal.ID)
		return nil
	}

	origBranchOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "rev-parse", "--abbrev-ref", "HEAD").CombinedOutput()
	if err != nil {
		return fmt.Errorf("git rev-parse --abbrev-ref HEAD: %v: %s", err, string(origBranchOut))
	}
	origBranch := strings.TrimSpace(string(origBranchOut))

	if cbOut, err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", "-b", branch).CombinedOutput(); err != nil {
		return fmt.Errorf("git checkout -b %s: %v: %s", branch, err, string(cbOut))
	}

	statusOut, _ := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "status", "--porcelain").CombinedOutput()
	if strings.TrimSpace(string(statusOut)) != "" {
		exec.CommandContext(ctx, "git", "-C", goal.Workspace, "add", "-A").Run()
		commitMsg := fmt.Sprintf("feat: resolve goal %d\n\nGenerated by sin-code daemon (autodev).\nCo-authored-by: sin-code-daemon <daemon@sin-code.local>", goal.ID)
		exec.CommandContext(ctx, "git", "-C", goal.Workspace, "commit", "-m", commitMsg).Run()
	}

	title := fmt.Sprintf("[Autodev] Goal #%d: %s", goal.ID, autodevTruncate(goal.Prompt, 60))
	body := fmt.Sprintf("## Automated PR\n**Goal:** %d\n**Verified:** %v\n**Turns:** %d\n\n%s", goal.ID, res.Verified, res.Turns, res.Summary)
	prOut, err := exec.CommandContext(ctx, "gh", "pr", "create", "--title", title, "--body", body, "--head", branch, "--base", "main").CombinedOutput()
	if err != nil {
		exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).Run()
		return fmt.Errorf("gh pr create: %v: %s", err, string(prOut))
	}
	fmt.Printf("daemon: goal %d PR created: %s\n", goal.ID, strings.TrimSpace(string(prOut)))

	if err := exec.CommandContext(ctx, "git", "-C", goal.Workspace, "checkout", origBranch).Run(); err != nil {
		fmt.Printf("daemon: goal %d warning: could not restore branch %s: %v\n", goal.ID, origBranch, err)
	}
	return nil
}

func autodevTruncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
