// SPDX-License-Identifier: MIT
// Purpose: autopr pipeline — apply trivial fixes (gofmt/goimports/
// stub tests) to a workspace, build a deterministic PR-body, and
// emit a JSON report. Issue #158 acceptance criteria:
//   - PR body is generated from the diff report (no LLM needed).
//   - The auto-fix is reversible (PR is opened, not merged).
//   - Coverage for the classifier >= 80% (verified in
//     classify_test.go).
// The pipeline does NOT call gh here — that lives in autopr_cmd.go
// behind the permission engine (M4) and is `ask`-classified for
// the PR-creation call.
package autopr

import (
	"fmt"
	"sort"
	"strings"
)

// Report is the autopr pipeline output. Consumed by autopr_cmd.go
// to render the PR body and to decide whether to call ghbridge.
type Report struct {
	Workspace      string   `json:"workspace"`
	Issues         []Issue  `json:"issues"`
	AutoFixable    []Issue  `json:"auto_fixable"`
	RequiresHuman  []Issue  `json:"requires_human"`
	WouldCreatePR  bool     `json:"would_create_pr"`
	PRTitle        string   `json:"pr_title"`
	PRBody         string   `json:"pr_body"`
	CommandsToRun  []string `json:"commands_to_run"`
}

// NewReport runs the classifier over `issues` and produces the
// pipeline report. It is pure: no I/O, no LLM. The actual fix
// execution is the caller's job (the command stays `ask` per M4).
func NewReport(workspace string, issues []Issue) *Report {
	fixable := TrivialAndMechanical(issues)
	var human []Issue
	for _, i := range issues {
		if i.Class == ClassNonTrivial {
			human = append(human, i)
		}
	}
	r := &Report{
		Workspace:     workspace,
		Issues:        issues,
		AutoFixable:   fixable,
		RequiresHuman: human,
	}
	if len(fixable) > 0 {
		r.WouldCreatePR = true
		r.PRTitle = renderPRTitle(fixable)
		r.PRBody = renderPRBody(workspace, fixable, human)
		r.CommandsToRun = renderCommands(fixable)
	}
	return r
}

// renderPRTitle returns "autopr: fix N trivial issues (<files>)".
// Stable, no LLM, deterministic.
func renderPRTitle(issues []Issue) string {
	files := uniqueFiles(issues)
	sort.Strings(files)
	if len(files) == 0 {
		return fmt.Sprintf("autopr: fix %d trivial issues", len(issues))
	}
	if len(files) == 1 {
		return fmt.Sprintf("autopr: fix %d trivial issues (%s)", len(issues), files[0])
	}
	return fmt.Sprintf("autopr: fix %d trivial issues (%s + %d more)",
		len(issues), files[0], len(files)-1)
}

// renderPRBody returns a deterministic Markdown body. Sections:
//   1. one-line summary
//   2. "Auto-fixable (N)" table
//   3. "Requires human (M)" table
//   4. "How to verify" section
//   5. footer with the verify-gate status
func renderPRBody(workspace string, fixable, human []Issue) string {
	var b strings.Builder
	b.WriteString("## Auto-PR (issue #158)\n\n")
	b.WriteString("This PR was opened automatically by `sin-code autopr` after a `task.complete`. ")
	b.WriteString("The pipeline classified the regressions; only the auto-fixable subset is included in this PR.\n\n")

	b.WriteString(fmt.Sprintf("**Workspace:** `%s`\n\n", workspace))
	b.WriteString(fmt.Sprintf("**Auto-fixable:** %d  |  **Requires human:** %d\n\n",
		len(fixable), len(human)))

	if len(fixable) > 0 {
		b.WriteString("### Auto-fixable\n\n")
		b.WriteString("| Class | Category | File | Note |\n")
		b.WriteString("|-------|----------|------|------|\n")
		for _, i := range fixable {
			b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s |\n",
				i.Class, i.Category, i.File, i.Note))
		}
		b.WriteString("\n")
	}

	if len(human) > 0 {
		b.WriteString("### Requires human\n\n")
		b.WriteString("These regressions were deferred to a human author:\n\n")
		b.WriteString("| Category | File | Note |\n")
		b.WriteString("|----------|------|------|\n")
		for _, i := range human {
			b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n",
				i.Category, i.File, i.Note))
		}
		b.WriteString("\n")
	}

	b.WriteString("### How to verify\n\n")
	b.WriteString("```sh\n")
	b.WriteString("go test -race -count=1 ./...\n")
	b.WriteString("go build ./...\n")
	b.WriteString("```\n\n")
	b.WriteString("The verify gate is the source of truth (M3). ")
	b.WriteString("If the gate is red, this PR must not be merged.\n\n")
	b.WriteString("---\n*Generated by `internal/autopr` — no LLM was called.*\n")
	return b.String()
}

// renderCommands returns the shell commands the pipeline would
// execute, in deterministic order.
func renderCommands(issues []Issue) []string {
	var cmds []string
	seen := map[string]bool{}
	for _, i := range issues {
		if i.Fix == "" || seen[i.Fix] {
			continue
		}
		seen[i.Fix] = true
		cmds = append(cmds, i.Fix)
	}
	sort.Strings(cmds)
	return cmds
}

// uniqueFiles returns the de-duplicated, sorted list of files
// referenced by issues.
func uniqueFiles(issues []Issue) []string {
	seen := map[string]bool{}
	var out []string
	for _, i := range issues {
		if i.File != "" && !seen[i.File] {
			seen[i.File] = true
			out = append(out, i.File)
		}
	}
	sort.Strings(out)
	return out
}
