// SPDX-License-Identifier: MIT
// Purpose: render a ScoredList to text, markdown, or JSON. The CLI
// uses Render(Format) to dispatch. The default Format is "text" for
// the TTY, "md" for `> BACKLOG.md` redirection (the issue's primary
// use case), and "json" for machine consumption.
package triage

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Format selects the renderer.
type Format string

const (
	FormatText Format = "text"
	FormatMD   Format = "md"
	FormatJSON Format = "json"
)

// Render writes the list to w in the chosen format. Render never
// returns an error from the render itself; the only error surface
// is the JSON encoder. The text and md renderers use Fprintf so a
// short write is silently truncated (the operator will see the
// truncation in the terminal).
func Render(w io.Writer, list ScoredList, f Format) error {
	switch f {
	case FormatJSON:
		return renderJSON(w, list)
	case FormatMD:
		return renderMD(w, list)
	default:
		return renderText(w, list)
	}
}

func renderJSON(w io.Writer, list ScoredList) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(list)
}

func renderText(w io.Writer, list ScoredList) error {
	// Header
	fmt.Fprintf(w, "Backlog: %d open issues, scored by triage heuristic\n", list.Total)
	fmt.Fprintf(w, "%s\n", strings.Repeat("─", 60))
	// Group by group key in deterministic order (score-desc within group)
	groups := groupInOrder(list)
	for _, g := range groups {
		fmt.Fprintf(w, "\n%s (%d)\n", g.key, len(g.items))
		for _, it := range g.items {
			fmt.Fprintf(w, "  %4d  %3d  #%-4d %s\n",
				it.Score, it.Score, it.Issue.Number, trim(it.Issue.Title, 60))
		}
	}
	fmt.Fprintf(w, "\n%s\n", strings.Repeat("─", 60))
	return nil
}

func renderMD(w io.Writer, list ScoredList) error {
	fmt.Fprintf(w, "# Backlog\n\n")
	fmt.Fprintf(w, "Auto-generated by `sin-code triage` (issue #162). ")
	fmt.Fprintf(w, "%d open issues, sorted by triage score.\n\n", list.Total)

	groups := groupInOrder(list)
	for _, g := range groups {
		fmt.Fprintf(w, "## %s (%d)\n\n", g.key, len(g.items))
		// Markdown table: score | # | title | signals
		fmt.Fprintf(w, "| Score | # | Title | Signals |\n")
		fmt.Fprintf(w, "|------:|---:|-------|---------|\n")
		for _, it := range g.items {
			title := strings.ReplaceAll(it.Issue.Title, "|", "\\|")
			signals := strings.Join(it.Reasons, ", ")
			fmt.Fprintf(w, "| %d | [#%d](%s) | %s | %s |\n",
				it.Score, it.Issue.Number, it.Issue.URL, title, signals)
		}
		fmt.Fprintf(w, "\n")
	}
	return nil
}

type groupBucket struct {
	key   string
	items []Scored
}

func groupInOrder(list ScoredList) []groupBucket {
	// Preserve score-desc overall order, but emit a section header
	// every time the group key changes. This gives stable grouping
	// for both the text and md renderer.
	if len(list.Items) == 0 {
		return nil
	}
	var out []groupBucket
	cur := groupBucket{key: list.Items[0].GroupKey}
	cur.items = append(cur.items, list.Items[0])
	for _, it := range list.Items[1:] {
		if it.GroupKey != cur.key {
			out = append(out, cur)
			cur = groupBucket{key: it.GroupKey}
		}
		cur.items = append(cur.items, it)
	}
	out = append(out, cur)

	// Also sort group sections by their highest score, descending.
	// This keeps the markdown stable when a new issue flips the
	// group order (e.g. a fresh loop-system issue outranks a stale
	// epic).
	sort.SliceStable(out, func(a, b int) bool {
		return out[a].items[0].Score > out[b].items[0].Score
	})
	return out
}

func trim(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
