"""Purpose: CEO Audit report generator — Markdown + SARIF + JSON + HTML.

Docs: report.doc.md
"""

from __future__ import annotations

import html
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Module overview ──────────────────────────────────────────────────
#
# This module produces FOUR report formats from a single score.json:
#
#   1. report.md     — Markdown, board-ready. Generated by make_markdown.
#                      Uses REPORT_TEMPLATE (below) + late-binding placeholders.
#   2. report.sarif  — SARIF 2.1.0 for GitHub Code Scanning. make_sarif.
#                      Auto-uploaded by the ceo-audit GitHub Action.
#   3. report.html   — Self-contained HTML, PDF-exportable. make_html.
#                      Inline CSS so no external assets required.
#   4. report.json   — Machine-readable, opt-in via --json flag.
#                      Includes flattened all_findings list for tooling.
#
# main() orchestrates all four — load score.json + per-axis findings,
# run each render, write each output file. Total runtime: < 100ms.
#
# Placeholder strategy: REPORT_TEMPLATE uses {var} for str.format AND
# {{TOKEN}} for the 3 late-binding sections (axis findings, action
# plan, all findings). main() fills those with str.replace after the
# initial format() pass — keeps make_markdown simple.
# ─────────────────────────────────────────────────────────────────────


# ── Markdown template (placeholders filled by make_markdown + main) ───
# Template uses double-braced `{var}` for str.format substitution, and
# `{{TOKEN}}` (literal braces) for late-binding placeholders that
# main() replaces via str.replace after str.format runs. See the three
# `{{AXIS_FINDINGS}}` / `{{ACTION_PLAN}}` / `{{ALL_FINDINGS}}` markers.
REPORT_TEMPLATE = """# CEO Audit — {repo_name}

**Generated:** {date}
**Profile:** {profile}
**Auditor:** CEO Audit v1.0 (SIN-Code Tool Suite)

---

## Executive Summary

| Metric | Value |
|--------|-------|
| **Audit complete** | **{audit_complete}** |
| **Grade** | **{grade}** |
| **Score** | **{score}/100** |
| **Total findings** | {total_findings} |
| **Critical** | {critical} |
| **High** | {high} |
| **Estimated fix cost** | ~{fix_hours} hours |
| **Top risk** | {top_risk_title} ({top_risk_severity}) |

{verdict_blurb}

{execution_status_md}

---

## Score Card

| Axis | Status | Gate coverage | Score | Weight | Weighted | Findings |
|------|--------|---------------|-------|--------|----------|----------|
{axis_table}

**Weighted total: {score}/100**

---

## Top 3 Risks

{top_risks_md}

---

## Findings by Severity

{severity_breakdown}

---

## Findings by Axis

{axis_findings_md}

---

## Compliance

| Standard | Coverage |
|----------|----------|
| **OWASP ASVS v5.0** | {owasp_pct}% of findings mapped to CWE |
| **CWE Top 25** | {top25_pct}% of findings in CWE Top 25 |
| **GDPR (data handling)** | {gdpr_pct}% of log-related findings |
| **SOC 2 (CC7)** | {soc2_pct}% of auth/access findings |

---

## Action Plan (ROI-ranked)

{action_plan_md}

---

## Regression vs Last Audit

{regression_md}

---

## Appendix: All Findings

<details>
<summary>Click to expand {total_findings} findings</summary>

{all_findings_md}

</details>

---

*Generated by CEO Audit — a 47-gate, 8-axis, SOTA review. Audited by the SIN-Code Tool Suite + best-of-breed external tools. [Read the SKILL.md](SKILL.md) to understand how it works.*
"""


# ── Helpers ──────────────────────────────────────────────────────────


def escape(s: str) -> str:
    """HTML-escape `s` for safe rendering in Markdown/HTML reports."""
    # Empty/None passes through as "" to keep f-strings clean.
    return html.escape(s) if s else ""


def grade_emoji(letter: str) -> str:
    """Map a letter grade (A+/A/B/C/D/F) to its display emoji."""
    # Emoji choices align with the executive-summary verdict severity.
    return {
        "A+": "🏆",
        "A": "✅",
        "B": "⚠️",
        "C": "⚠️",
        "D": "❌",
        "F": "🛑",
    }.get(letter, "?")


def grade_verdict(letter: str) -> str:
    """Return the executive-summary blurb for a grade letter."""
    # One-paragraph verdicts — read aloud at the start of every report.
    # Wording is deliberate: each blurb tells the reader what to DO next.
    verdicts = {
        "A+": "**SOTA-ready. Ship it.** This codebase meets the highest standard of security, quality, and maintainability. Deploy with confidence.",
        "A": "**Production-ready.** Minor polish items remain but no blockers. Safe to deploy to production.",
        "B": "**Acceptable with monitoring.** Plan to address findings within the current sprint. Safe to deploy with additional logging and alerting on affected paths.",
        "C": "**Not production-ready.** Significant work needed. Use in staging or with feature flags only. Address HIGH and CRITICAL findings before next release.",
        "D": "**Significant risk.** Halt production deployment. Address all CRITICAL and HIGH findings. Consider a security review before continuing.",
        "F": "**Halt.** Critical security or correctness issues present. Do not deploy. Address all CRITICAL findings immediately and schedule a follow-up audit.",
    }
    return verdicts.get(letter, "Unknown grade")


# ── Markdown report assembly ─────────────────────────────────────────


def make_markdown(score: dict, repo_name: str, profile: str) -> str:
    """Render the Markdown report from a score dict.

    Args:
        score:     The dict produced by `score.py` (axes + grade + findings).
        repo_name: Display name of the audited repo (basename).
        profile:   Audit profile name (FULL / SECURITY / RELEASE / QUICK).

    Returns:
        Markdown text. Three placeholders (`{{AXIS_FINDINGS}}`,
        `{{ACTION_PLAN}}`, `{{ALL_FINDINGS}}`) remain in the output —
        they are filled in by `main()` after all per-axis JSONs are loaded.
    """
    # ── Axis table row builder (one row per audited axis) ───────────
    # Each row: | Axis | Score | Weight | Weighted | Findings |
    # Rendered in the Score Card section of the report header.
    axis_rows = []
    for ax, ax_data in score.get("axes", {}).items():
        weight = score.get("weights", {}).get(ax, 0)
        # Weighted contribution: each axis score scaled by its weight.
        # Round to 1 decimal — matches the precision in score.json.
        weighted = round(ax_data["score"] * weight, 1)
        # f-string with format specifiers: % for percentage, no comma for int.
        status = ax_data.get("status", "complete")
        coverage = float(ax_data.get("gate_coverage", 1.0))
        skipped = int(ax_data.get("skipped_gate_count", 0))
        coverage_label = f"{coverage:.0%}" + (f" ({skipped} skipped)" if skipped else "")
        axis_rows.append(
            f"| {ax.capitalize()} | {status} | {coverage_label} | {ax_data['score']} | "
            f"{weight:.0%} | {weighted} | {ax_data['finding_count']} |"
        )
    axis_table = "\n".join(axis_rows)

    # ── Top 3 risks (already ranked by score.py) ────────────────────
    # Pre-ranked by score.py's risk_score (likelihood × impact).
    # Renders as bullet list under "Top 3 Risks" section.
    top_md = []
    for r in score.get("top_3_risks", []):
        top_md.append(f"- **{r.get('severity')}** — {r.get('title')} (risk: {r.get('risk_score')})")
    top_risks_md = "\n".join(top_md) or "_No significant risks detected._"

    # ── Severity breakdown (sorted for stable diff in CI) ───────────
    # Sorted alphabetically so the same severities appear in the same order
    # across runs — CI diff stays minimal.
    sev_counts = score.get("severity_counts", {})
    breakdown = "\n".join(f"- **{s}**: {n}" for s, n in sorted(sev_counts.items()))

    # ── Top risk = first entry of top_3_risks (used in header table) ─
    # Empty-safe: if no risks, top_risk is an empty dict and
    # `top_risk.get("title", "—")` falls through to the dash.
    top_risks = score.get("top_3_risks", [])
    top_risk = top_risks[0] if top_risks else {}

    # Per-axis findings (will need to load them from run_dir)
    # This is set later by main()

    # Action plan
    # (set later)

    # ── Regression summary (only meaningful from 2nd audit onward) ──
    # First-ever audit on a repo → "No previous audit to compare."
    # Subsequent audits → bullet list of new + fixed counts.
    reg = score.get("regression", {})
    if reg.get("new", 0) == 0 and reg.get("fixed", 0) == 0:
        regression_md = "_No previous audit to compare._"
    else:
        regression_md = f"- **{reg.get('new', 0)}** new findings\n- **{reg.get('fixed', 0)}** findings fixed since last audit"

    audit_complete = bool(score.get("audit_complete", True))
    audit_errors = score.get("audit_errors", [])
    if audit_complete:
        execution_status_md = "✅ **Execution status:** all requested audit axes completed."
    else:
        error_lines = "\n".join(f"- {escape(str(error))}" for error in audit_errors)
        execution_status_md = (
            "🚫 **Execution status: INCOMPLETE.** The grade is forced to F and "
            "must not be interpreted as a repository quality score.\n\n"
            + (error_lines or "- Unknown audit execution error")
        )

    # ── Fill the report template — placeholders stay for main() ─────
    # Each kwarg corresponds to a {var} placeholder in REPORT_TEMPLATE.
    # `{{TOKEN}}` markers are left intact for main() to replace later.
    return REPORT_TEMPLATE.format(
        repo_name=escape(repo_name),
        # ISO-8601 UTC timestamp — stable across CI machines + time zones.
        date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        profile=escape(profile),
        # Grade is rendered with an emoji prefix for visual scannability.
        audit_complete="yes" if audit_complete else "NO",
        grade=f"{grade_emoji(score.get('grade', '?'))} {score.get('grade')}",
        score=score.get("score", 0),
        total_findings=score.get("total_findings", 0),
        critical=score.get("critical", 0),
        high=score.get("high", 0),
        # Estimated total engineer-hours (rounded) — set by score.py.
        fix_hours=score.get("total_fix_hours_est", 0),
        top_risk_title=escape(top_risk.get("title", "—")),
        top_risk_severity=escape(top_risk.get("severity", "—")),
        # Verdict blurb is grade-specific (see grade_verdict above).
        verdict_blurb=grade_verdict(score.get("grade", "?")),
        execution_status_md=execution_status_md,
        axis_table=axis_table,
        top_risks_md=top_risks_md,
        severity_breakdown=breakdown or "_No findings._",
        axis_findings_md="{{AXIS_FINDINGS}}",  # placeholder, filled in main
        # % of findings tagged with a CWE-* ID (rough OWASP coverage proxy).
        owasp_pct=int(
            100
            * score.get("compliance", {}).get("owasp_cwe_findings", 0)
            / max(score.get("total_findings", 1), 1)
        ),
        # Compliance percentages — computed externally; stubbed here.
        top25_pct=int(100 * 0.0),  # computed separately
        gdpr_pct=0,  # computed separately
        soc2_pct=0,  # computed separately
        # Placeholder pair — filled by main() after the per-axis JSONs load.
        action_plan_md="{{ACTION_PLAN}}",  # placeholder
        regression_md=regression_md,
        all_findings_md="{{ALL_FINDINGS}}",  # placeholder
    )


# ── SARIF output (GitHub Code Scanning) ──────────────────────────────


def parse_source_location(value: str) -> tuple[str, int] | None:
    """Parse the scanners' portable ``path:line`` location contract."""
    if not isinstance(value, str) or ":" not in value:
        return None
    path, line_text = value.rsplit(":", 1)
    try:
        line = int(line_text)
    except ValueError:
        return None
    if not path or line < 1:
        return None
    return path, line


def sarif_physical_location(value: str) -> dict | None:
    parsed = parse_source_location(value)
    if parsed is None:
        return None
    path, line = parsed
    return {
        "artifactLocation": {"uri": path},
        "region": {"startLine": line},
    }


def make_sarif(score: dict, run_dir: Path) -> dict:
    """Generate SARIF 2.1.0 output for GitHub Code Scanning."""
    # SARIF = Static Analysis Results Interchange Format
    # GitHub uploads this file via the upload-sarif Action and surfaces
    # each finding in the "Security" tab of the repository.
    results = []
    # Walk every axis → every finding, flatten into a single SARIF results list.
    for ax_name, ax_data in score.get("axes", {}).items():
        for f in ax_data.get("findings", []):
            sev = f.get("severity", "INFO").upper()
            # SARIF only has 3 levels — collapse our 5-level scale into them.
            # CRITICAL+HIGH → error, MEDIUM → warning, LOW/INFO → note.
            # Unknown severities → "note" (safe default, lowest priority).
            sarif_level = {
                "CRITICAL": "error",
                "HIGH": "error",
                "MEDIUM": "warning",
                "LOW": "note",
            }.get(sev, "note")
            source_locations = [
                physical
                for value in f.get("locations", [])
                if (physical := sarif_physical_location(value)) is not None
            ]
            result = {
                # ruleId is required by SARIF spec — fall back to "unknown" if missing.
                "ruleId": f.get("gate", "unknown"),
                "level": sarif_level,
                # Message text: title + description for context.
                "message": {"text": f"{f.get('title')}: {f.get('description', '')}"},
                "properties": {
                    # security-severity (0.0-10.0) drives GitHub's "severity" column.
                    # Calibrated to match CVSS-like scoring conventions.
                    "security-severity": str(
                        {"CRITICAL": 9.5, "HIGH": 8.0, "MEDIUM": 5.0, "LOW": 2.0, "INFO": 0.1}.get(
                            sev, 1.0
                        )
                    ),
                    # Pass-through CWE for GitHub's "Most common weaknesses" panel.
                    "cwe": f.get("cwe", ""),
                    # Pass-through fix recommendation for the SARIF viewer.
                    "fix": f.get("fix", ""),
                    # Axis name for our own grouping (not in standard SARIF).
                    "axis": ax_name,
                    "occurrence-count": f.get("occurrence_count", len(f.get("locations", [])) or 1),
                },
            }
            if source_locations:
                result["locations"] = [{"physicalLocation": source_locations[0]}]
                result["relatedLocations"] = [
                    {"id": index, "physicalLocation": physical}
                    for index, physical in enumerate(source_locations[1:11], start=1)
                ]
            results.append(result)
    # SARIF 2.1.0 envelope — schema URL is mandatory for GitHub upload.
    # The "runs" array allows multiple tool runs; we always emit one.
    return {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                # Driver metadata — shown in the GitHub Code Scanning UI.
                "tool": {
                    "driver": {
                        "name": "CEO Audit",
                        "version": "1.0.0",
                        "informationUri": "https://opensin.dev/ceo-audit",
                        # `rules` is empty: we don't pre-declare rules, GitHub infers.
                        "rules": [],
                    }
                },
                "results": results,
            }
        ],
    }


# ── HTML output (self-contained, PDF-exportable) ────────────────────


def make_html(score: dict, repo_name: str) -> str:
    """Generate a self-contained HTML report (PDF-exportable)."""
    # The HTML is fully self-contained — inline CSS, no external assets,
    # no JS. This makes it safe to email, archive, or print to PDF.
    sev_counts = score.get("severity_counts", {})
    rows = []
    # One <tr> per axis — same schema as Markdown's Score Card table.
    for ax, d in score.get("axes", {}).items():
        coverage = float(d.get("gate_coverage", 1.0))
        skipped = int(d.get("skipped_gate_count", 0))
        rows.append(
            f"<tr><td>{escape(ax)}</td><td>{coverage:.0%} ({skipped} skipped)</td>"
            f"<td>{d['score']}</td><td>{d['finding_count']}</td></tr>"
        )
    rows_html = "\n".join(rows)
    # `+` in the grade class needs an escaped CSS selector (`.grade-A\+`).
    # html.escape doesn't escape `+` — that's a CSS-specific concern.
    grade_esc = escape(score.get("grade", "F")).replace("+", r"\+")
    # Inline <style> so the HTML works without an external CSS file.
    # Color palette: green for good grades, amber for B/C, red for D/F.
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>CEO Audit — {escape(repo_name)}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #222; }}
h1 {{ color: #1a3a52; }}
.grade-A\\+ {{ color: #0a8043; }} .grade-A {{ color: #1a8043; }}
.grade-B, .grade-C {{ color: #c08b00; }} .grade-D, .grade-F {{ color: #c00; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background: #f5f5f5; }}
.metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
.metric .label {{ display: block; font-size: 12px; color: #666; }}
.metric .value {{ font-size: 24px; font-weight: bold; }}
.critical {{ background: #fee; padding: 10px; border-left: 4px solid #c00; margin: 10px 0; }}
</style></head><body>
<h1>CEO Audit — {escape(repo_name)}</h1>
<p><strong>Generated:</strong> {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}</p>
<div class="metric"><span class="label">Grade</span><span class="value grade-{grade_esc}">{escape(score.get("grade", "?"))}</span></div>
<div class="metric"><span class="label">Score</span><span class="value">{score.get("score", 0)}/100</span></div>
<div class="metric"><span class="label">Findings</span><span class="value">{score.get("total_findings", 0)}</span></div>
<div class="metric"><span class="label">Critical</span><span class="value">{score.get("critical", 0)}</span></div>
<div class="metric"><span class="label">High</span><span class="value">{score.get("high", 0)}</span></div>
<h2>Score Card</h2>
<table><tr><th>Axis</th><th>Gate coverage</th><th>Score</th><th>Findings</th></tr>
{rows_html}
</table>
<h2>Severity Breakdown</h2>
<ul>
{"".join(f"<li><strong>{escape(s)}</strong>: {n}</li>" for s, n in sorted(sev_counts.items()))}
</ul>
<p><em>Generated by CEO Audit v1.0 — part of the SIN-Code Tool Suite.</em></p>
</body></html>"""


# ── CLI entry point ──────────────────────────────────────────────────


def main():
    """CLI entry point — load score.json + per-axis findings, write all reports.

    Args (from sys.argv):
        repo_path:   Absolute path to the audited repo.
        run_dir:     Directory where score.json + findings/ already exist.
        profile:     Audit profile name (FULL / SECURITY / RELEASE / QUICK).
        write_json:  Truthy → also emit report.json sidecar.

    Side effects:
        Writes report.md, report.sarif, report.html (and optionally
        report.json) into `run_dir`. Prints a one-line summary to stdout.

    Exits:
        1 if fewer than 4 positional args were given.
    """
    if len(sys.argv) < 5:
        print("Usage: report.py <repo_path> <run_dir> <profile> <write_json>", file=sys.stderr)
        sys.exit(1)

    repo_path = Path(sys.argv[1]).resolve()
    run_dir = Path(sys.argv[2])
    profile = sys.argv[3]
    # write_json: accept multiple truthy spellings for shell convenience.
    write_json = sys.argv[4].lower() in ("1", "true", "yes")

    score_data = json.loads((run_dir / "score.json").read_text())

    # ── Load all axis findings (so we have full details) ──────────────
    for ax_name in score_data.get("axes", {}):
        f = run_dir / "findings" / f"{ax_name}.json"
        if f.exists():
            data = json.loads(f.read_text())
            score_data["axes"][ax_name]["findings"] = data.get("findings", [])

    # ── Load ROI-ranked action plan (optional sidecar) ────────────────
    action_plan = []
    ap = run_dir / "action_plan.json"
    if ap.exists():
        action_plan = json.loads(ap.read_text())

    repo_name = repo_path.name

    # ── Build the per-axis findings section ──────────────────────────
    # We render up to 10 findings per axis to keep the report scannable.
    # The remainder is summarised as `_...and N more. See findings/<ax>.json._`.
    # The 10-per-axis cap is the SOTA balance between detail and readability.
    axis_md = []
    for ax_name, ax_data in score_data.get("axes", {}).items():
        findings = ax_data.get("findings", [])
        if not findings:
            # Skip empty axes entirely — no heading, no empty section.
            continue
        # Section heading lists the finding count for quick scanning.
        axis_md.append(f"\n### {ax_name.capitalize()} ({len(findings)} findings)\n")
        for f in findings[:10]:  # top 10 per axis
            # Defensive .get() with sensible defaults — never KeyError.
            sev = f.get("severity", "INFO")
            risk = f.get("risk_score", 0)
            title = f.get("title", "")
            desc = f.get("description", "")
            fix = f.get("fix", "")
            locations = f.get("locations", [])
            location_line = f"  - Locations: {', '.join(locations[:5])}\n" if locations else ""
            axis_md.append(
                f"- **[{sev}]** {title} (risk: {risk})\n  - {desc}\n{location_line}  - Fix: {fix}\n"
            )
        if len(findings) > 10:
            # Don't drop the data — point readers to the raw JSON.
            axis_md.append(f"- _...and {len(findings) - 10} more. See `findings/{ax_name}.json`._")
    axis_findings_md = "\n".join(axis_md) or "_No findings._"

    # ── Build action plan section (top 10 by ROI) ────────────────────
    # action_plan is already sorted by ROI (descending) by score.py.
    # We render the first 10 entries — the highest-value fixes first.
    ap_md = []
    for i, item in enumerate(action_plan[:10], 1):
        # Each item: severity + title + hours estimate + ROI score + fix.
        ap_md.append(
            f"{i}. **[{item.get('severity', '?')}]** {item.get('title', '?')} "
            f"— ~{item.get('fix_hours_est', 0)}h, ROI: {item.get('roi', 0):.2f}\n"
            f"   - {item.get('fix', '—')}"
        )
    action_plan_md = "\n".join(ap_md) or "_No action items._"

    # ── Build all-findings appendix (collapsible <details> in report) ─
    # No cap here — the appendix is collapsible so it can be long.
    all_findings_md = []
    for ax_name, ax_data in score_data.get("axes", {}).items():
        for f in ax_data.get("findings", []):
            # Full 7-field record: gate, axis, severity, CWE, risk, desc, fix.
            all_findings_md.append(
                f"### {f.get('gate', '?')} — {f.get('title', '?')}\n"
                f"- **Axis:** {ax_name}\n"
                f"- **Severity:** {f.get('severity', '?')}\n"
                f"- **CWE:** {f.get('cwe', '—')}\n"
                f"- **Risk score:** {f.get('risk_score', 0)}\n"
                f"- **Description:** {f.get('description', '—')}\n"
                f"- **Fix:** {f.get('fix', '—')}\n"
            )
    all_findings_md = "\n".join(all_findings_md) or "_No findings._"

    # ── Render: fill placeholders left by make_markdown() ────────────
    md = make_markdown(score_data, repo_name, profile)
    md = md.replace("{{AXIS_FINDINGS}}", axis_findings_md)
    md = md.replace("{{ACTION_PLAN}}", action_plan_md)
    md = md.replace("{{ALL_FINDINGS}}", all_findings_md)

    # ── Write all formats in lockstep (atomic-enough for our purposes) ─
    (run_dir / "report.md").write_text(md)
    (run_dir / "report.sarif").write_text(json.dumps(make_sarif(score_data, run_dir), indent=2))
    (run_dir / "report.html").write_text(make_html(score_data, repo_name))
    if write_json:
        # JSON sidecar: machine-readable, includes flattened findings list.
        (run_dir / "report.json").write_text(
            json.dumps(
                {
                    "score": score_data,
                    "action_plan": action_plan,
                    "all_findings": [
                        {**f, "axis": ax}
                        for ax, d in score_data.get("axes", {}).items()
                        for f in d.get("findings", [])
                    ],
                },
                indent=2,
            )
        )
    print(f"Reports written to: {run_dir}/")
    print("  • report.md     (Markdown, board-ready)")
    print("  • report.sarif  (SARIF 2.1.0, GitHub-compatible)")
    print("  • report.html   (HTML, PDF-exportable)")
    if write_json:
        print("  • report.json   (programmatic)")


if __name__ == "__main__":
    main()
