// SPDX-License-Identifier: MIT
// Purpose: config — view and manage sin-code configuration files.
// Supports reading, setting, and listing configuration values.
// Docs: config.doc.md
package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var ConfigCmd = &cobra.Command{
	Use:   "config",
	Short: "View and manage sin-code configuration",
	Long: `Manage sin-code configuration files and settings.

Configuration files:
  ~/.config/sin/sin-code.toml    Main configuration (theme, defaults)
  ~/.config/sin/tui.toml         TUI preferences (theme, keybindings)

Subcommands:
  config get <key>          Get a configuration value
  config set <key> <value>  Set a configuration value
  config list               List all configuration values
  config path               Show configuration directory path
  config init               Create default configuration files`,
}

var configGetCmd = &cobra.Command{
	Use:   "get <key>",
	Short: "Get a configuration value",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key := args[0]
		val, err := getConfigValue(key)
		if err != nil {
			return err
		}
		fmt.Println(val)
		return nil
	},
}

var configSetCmd = &cobra.Command{
	Use:   "set <key> <value>",
	Short: "Set a configuration value",
	Args:  cobra.ExactArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		key, value := args[0], args[1]
		return setConfigValue(key, value)
	},
}

var configListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all configuration values",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := loadConfig()
		if err != nil {
			return err
		}
		fmt.Printf("Configuration directory: %s\n", configDir())
		fmt.Println()
		fmt.Printf("theme              = %q\n", cfg.Theme)
		fmt.Printf("default_timeout    = %d\n", cfg.DefaultTimeout)
		fmt.Printf("default_format     = %q\n", cfg.DefaultFormat)
		fmt.Printf("mcp_server_enabled = %v\n", cfg.MCPServerEnabled)
		return nil
	},
}

var configPathCmd = &cobra.Command{
	Use:   "path",
	Short: "Show configuration directory path",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println(configDir())
		return nil
	},
}

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Create default configuration files",
	RunE: func(cmd *cobra.Command, args []string) error {
		return initConfig()
	},
}

func init() {
	ConfigCmd.AddCommand(configGetCmd)
	ConfigCmd.AddCommand(configSetCmd)
	ConfigCmd.AddCommand(configListCmd)
	ConfigCmd.AddCommand(configPathCmd)
	ConfigCmd.AddCommand(configInitCmd)
}

// ─── Config data model ─────────────────────────────────────────────────────

type SinCodeConfig struct {
	Theme            string `toml:"theme"`
	DefaultTimeout   int    `toml:"default_timeout"`
	DefaultFormat    string `toml:"default_format"`
	MCPServerEnabled bool   `toml:"mcp_server_enabled"`
}

func defaultConfig() SinCodeConfig {
	return SinCodeConfig{
		Theme:            "dark",
		DefaultTimeout:   60,
		DefaultFormat:    "json",
		MCPServerEnabled: true,
	}
}

// ─── Config file operations ────────────────────────────────────────────────

func configDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".config", "sin")
}

func configFilePath() string {
	return filepath.Join(configDir(), "sin-code.toml")
}

func loadConfig() (SinCodeConfig, error) {
	cfg := defaultConfig()
	path := configFilePath()
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return cfg, fmt.Errorf("read config: %w", err)
	}
	// Simple TOML-like parsing (key = value)
	lines := string(data)
	for _, line := range strings.Split(lines, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.Trim(strings.TrimSpace(parts[1]), `"`)
		switch key {
		case "theme":
			cfg.Theme = val
		case "default_timeout":
			fmt.Sscanf(val, "%d", &cfg.DefaultTimeout)
		case "default_format":
			cfg.DefaultFormat = val
		case "mcp_server_enabled":
			cfg.MCPServerEnabled = val == "true"
		}
	}
	return cfg, nil
}

func saveConfig(cfg SinCodeConfig) error {
	 dir := configDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	path := configFilePath()
	content := fmt.Sprintf(`# sin-code configuration
# Generated by 'sin-code config init'. Edit manually or use 'sin-code config set'.

# TUI theme: "dark" or "light"
theme = %q

# Default timeout for long-running commands (seconds)
default_timeout = %d

# Default output format: "text" or "json"
default_format = %q

# Enable MCP server by default when running 'sin-code serve'
mcp_server_enabled = %v
`, cfg.Theme, cfg.DefaultTimeout, cfg.DefaultFormat, cfg.MCPServerEnabled)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

func initConfig() error {
	cfg := defaultConfig()
	if err := saveConfig(cfg); err != nil {
		return err
	}
	fmt.Printf("✅ Created default configuration at %s\n", configFilePath())
	fmt.Printf("   Theme: %s\n", cfg.Theme)
	fmt.Printf("   Default timeout: %d seconds\n", cfg.DefaultTimeout)
	fmt.Printf("   Default format: %s\n", cfg.DefaultFormat)
	fmt.Printf("   MCP server enabled: %v\n", cfg.MCPServerEnabled)
	fmt.Println()
	fmt.Println("Tip: Use 'sin-code config set theme light' to switch themes.")
	return nil
}

func getConfigValue(key string) (string, error) {
	cfg, err := loadConfig()
	if err != nil {
		return "", err
	}
	switch key {
	case "theme":
		return cfg.Theme, nil
	case "default_timeout":
		return fmt.Sprintf("%d", cfg.DefaultTimeout), nil
	case "default_format":
		return cfg.DefaultFormat, nil
	case "mcp_server_enabled":
		return fmt.Sprintf("%v", cfg.MCPServerEnabled), nil
	default:
		return "", fmt.Errorf("unknown config key: %q (known: theme, default_timeout, default_format, mcp_server_enabled)", key)
	}
}

func setConfigValue(key, value string) error {
	cfg, err := loadConfig()
	if err != nil {
		return err
	}
	switch key {
	case "theme":
		if value != "dark" && value != "light" {
			return fmt.Errorf("theme must be 'dark' or 'light', got %q", value)
		}
		cfg.Theme = value
	case "default_timeout":
		var timeout int
		if _, err := fmt.Sscanf(value, "%d", &timeout); err != nil {
			return fmt.Errorf("invalid timeout: %w", err)
		}
		cfg.DefaultTimeout = timeout
	case "default_format":
		if value != "text" && value != "json" {
			return fmt.Errorf("format must be 'text' or 'json', got %q", value)
		}
		cfg.DefaultFormat = value
	case "mcp_server_enabled":
		cfg.MCPServerEnabled = value == "true"
	default:
		return fmt.Errorf("unknown config key: %q (known: theme, default_timeout, default_format, mcp_server_enabled)", key)
	}
	if err := saveConfig(cfg); err != nil {
		return err
	}
	fmt.Printf("✅ Set %s = %q\n", key, value)
	return nil
}

