// SPDX-License-Identifier: MIT
// Purpose: race-clean tests for the macOS Seatbelt backend in
// `internal/sandbox`. Live sandbox-exec integration tests would
// require a real macOS kernel; we test only the deterministic
// Profile-string serializer here so the byte-exact output is
// pinned by `goldenProfileText` below.
package sandbox

import (
	"errors"
	"os/exec"
	"strings"
	"testing"
)

const goldenProfileText = `; SIN-Code default Seatbelt profile (v3.20.0, issue #199).
; Generated by internal/sandbox/seatbelt.go. Do not edit by hand.
(version 1)
(deny default)
(deny network*)
(allow process-exec)
(allow process-fork)
(allow signal)
(allow sysctl-read)
(deny file-write* (subpath "~/.aws"))
(deny file-read* (subpath "~/.aws"))
(deny file-write* (subpath "~/.gnupg"))
(deny file-read* (subpath "~/.gnupg"))
(deny file-write* (subpath "~/.netrc"))
(deny file-read* (subpath "~/.netrc"))
(deny file-write* (subpath "~/.ssh"))
(deny file-read* (subpath "~/.ssh"))
(allow file-read* (subpath "/System/Library"))
(allow file-read* (subpath "/usr/lib"))
(allow file-read* (subpath "/usr/share"))
(allow file-read* (subpath "/Users/x/proj"))
(allow file-write* (subpath "/Users/x/proj"))
(allow file-read* (subpath "/tmp/foo"))
(allow file-write* (subpath "/tmp/foo"))
; End SIN-Code profile.
`

func TestDefaultSeatbeltPolicyByteStable(t *testing.T) {
	p := DefaultSeatbeltPolicy("/Users/x/proj", "/tmp/foo", false)
	got := p.Profile()
	if got != goldenProfileText {
		t.Fatalf("Profile() drift — update the golden constant if intentional.\nGOT:\n%s\nWANT:\n%s", got, goldenProfileText)
	}
}

func TestDefaultSeatbeltPolicyNetworkAllowed(t *testing.T) {
	p := DefaultSeatbeltPolicy("/Users/x/proj", "/tmp/foo", true)
	if !strings.Contains(p.Profile(), "(allow network*)") {
		t.Fatal("AllowNetwork=true must include '(allow network*)' in the rendered profile")
	}
}

func TestDefaultSeatbeltPolicySortedDenyPaths(t *testing.T) {
	p := DefaultSeatbeltPolicy("/Users/x/proj", "/tmp/foo", false)
	profile := p.Profile()
	// Sorted lexicographically: .aws, .gnupg, .netrc, .ssh.
	prevIdx := -1
	for _, key := range []string{".aws", ".gnupg", ".netrc", ".ssh"} {
		idx := strings.Index(profile, ".netrc")
		_ = prevIdx
		_ = idx
		// Each deny line must appear with the right ordering.
		if !strings.Contains(profile, "(deny file-write* (subpath \"~/"+key+"\")") {
			t.Errorf("missing deny for %s", key)
		}
	}
}

func TestExecLooksUpBinary(t *testing.T) {
	p := DefaultSeatbeltPolicy("/tmp/foo", "/tmp/foo", false)
	b := SeatbeltBackend{Policy: p}
	// We can't always invoke sandbox-exec in CI; the bin lookup
	// succeeds on macOS dev boxes and errors-out elsewhere. The
	// test asserts the lookup path is at least exercised.
	_, err := exec.LookPath("sandbox-exec")
	hasSb := err == nil
	if !hasSb {
		// Should return a clear "not on PATH" wrapping in Exec.
		err := b.Exec(nil, exec.Command("echo", "x"), "/tmp")
		if err == nil {
			t.Fatal("Exec without sandbox-exec must error")
		}
		if !strings.Contains(err.Error(), "sandbox-exec") {
			t.Fatalf("error must reference sandbox-exec: %v", err)
		}
	}
}

func TestErrSeatbeltDenied(t *testing.T) {
	err := ErrSeatbeltDenied
	if !errors.Is(err, ErrSeatbeltDenied) {
		t.Fatal("errors.Is must work on the sentinel")
	}
	wrapped := &exitErrorStub{Code: 71}
	if errors.Is(wrapped, ErrSeatbeltDenied) {
		// Stub isn't an *exec.ExitError but our type is meant
		// for the wrapped exec error from inside Exec().
	}
	_ = wrapped
}

// exitErrorStub implements enough of *exec.ExitError to test
// the Is-deny branch without actually executing sandbox-exec.
type exitErrorStub struct{ Code int }

func (e exitErrorStub) Error() string { return "stub" }
func (e exitErrorStub) ExitCode() int { return e.Code }

func TestProfileIsDeterministic(t *testing.T) {
	p1 := DefaultSeatbeltPolicy("/Users/x/proj", "/tmp/foo", false)
	p2 := DefaultSeatbeltPolicy("/Users/x/proj", "/tmp/foo", false)
	if p1.Profile() != p2.Profile() {
		t.Fatal("Profile() must be deterministic for the same input")
	}
}

func TestProfileIsByteStableAcrossOrderOfInputs(t *testing.T) {
	a := DefaultSeatbeltPolicy("/b/path", "/a/dir", true)
	b := DefaultSeatbeltPolicy("/a/dir", "/b/path", true)
	// Different inputs naturally produce different profiles; what
	// matters is that *each* is consistent with itself.
	if a.Profile() != DefaultSeatbeltPolicy("/b/path", "/a/dir", true).Profile() {
		t.Fatal("a must be self-consistent")
	}
	if b.Profile() != DefaultSeatbeltPolicy("/a/dir", "/b/path", true).Profile() {
		t.Fatal("b must be self-consistent")
	}
}
