// SPDX-License-Identifier: MIT
// Purpose: macOS sandbox-exec (Seatbelt) backend for `internal/sandbox`.
// Mirrors Anthropic Claude Code's `seatbelt` backend (Anthropic release
// v2.1, 2026-01-22) so SIN-Code can ship a hot-path sandbox even on
// the macOS developer boxes where Landlock is unavailable.
//
// Defence-in-depth:
//   - The Seatbelt policy string is constructed deterministically from
//     a typed Policy struct (byte-stable for golden tests).
//   - The backend is FAIL-CLOSED: any sandbox-exec invocation that
//     produces a "deny" verdict is propagated as a typed error
//     (ErrSeatbeltDenied) so the caller can choose abort-vs-fallback.
//   - Tests construct the policy string only; live-exec tests would
//     require a real macOS kernel and are out of scope for this PR.
//
// M2: zero new deps. Pure Go strings + os/exec sandbox-exec.
package sandbox

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// ErrSeatbeltDenied is returned when sandbox-exec reports the operation
// would be denied under the policy. Callers can errors.As this and
// choose to abort the operation or attempt a less-strict fallback.
var ErrSeatbeltDenied = errors.New("sandbox: seatbelt denied operation")

// SeatbeltBackend constructs a Command wrapper that prefixes every
// exec with `sandbox-exec -p <policy>`. DefaultPolicy translates
// the project's standard read/write deny list into a sandbox profile
// string.
type SeatbeltBackend struct {
	Policy SeatbeltPolicy
}

// SeatbeltPolicy holds the typed fields of a Seatbelt profile. The
// produced profile string is byte-stable for given inputs so the
// golden test in `sandbox_seatbelt_test.go` can pin it.
type SeatbeltPolicy struct {
	// ReadWrite lists paths the sandboxed process MAY read AND write.
	ReadWrite []string
	// ReadOnly lists paths the sandboxed process MAY read but NOT write.
	ReadOnly []string
	// Deny lists paths that must NEVER be touched.
	Deny []string
	// AllowNetwork controls whether the policy permits network syscalls.
	AllowNetwork bool
}

// DefaultSeatbeltPolicy returns the project's standard policy for
// running `sin_bash` (or any user command) inside an agent session.
// It mirrors the Landlock `DefaultPolicy` semantics on macOS:
// permitted RW: working dir + tmp; permitted R: stdlib /usr/lib;
// deny: ~/.ssh, ~/.aws, ~/.gnupg. Network is opt-in via opt flag.
func DefaultSeatbeltPolicy(workdir, tmpDir string, allowNetwork bool) SeatbeltPolicy {
	p := SeatbeltPolicy{
		ReadWrite:    []string{workdir, tmpDir},
		ReadOnly:     []string{"/usr/lib", "/usr/share", "/System/Library"},
		AllowNetwork: allowNetwork,
	}
	// Add user home directories as deny-by-default — the sandbox
	// file-rules section below applies a global deny first then
	// permits only entries in ReadWrite/ReadOnly.
	for _, home := range []string{".ssh", ".aws", ".gnupg", ".netrc"} {
		p.Deny = append(p.Deny, filepath.Join("~", home))
	}
	return p
}

// Profile returns the literal SBPL policy string. UTF-8 only, ASCII
// where possible (sandbox-exec drops UTF-8 only if mal-encoded).
//
// Construction is deterministic: every[] slice is sorted before
// emission and a stable header is emitted first.
func (p SeatbeltPolicy) Profile() string {
	var sb strings.Builder
	sb.WriteString("; SIN-Code default Seatbelt profile (v3.20.0, issue #199).\n")
	sb.WriteString("; Generated by internal/sandbox/seatbelt.go. Do not edit by hand.\n")
	sb.WriteString("(version 1)\n")
	sb.WriteString("(deny default)\n")
	if p.AllowNetwork {
		sb.WriteString("(allow network*)\n")
	} else {
		sb.WriteString("(deny network*)\n")
	}
	// Process inheritance per Apple's reference profile.
	sb.WriteString("(allow process-exec)\n")
	sb.WriteString("(allow process-fork)\n")
	sb.WriteString("(allow signal)\n")
	sb.WriteString("(allow sysctl-read)\n")
	// File rules: deny first, then read-only, then read-write.
	for _, d := range sortedPaths(p.Deny) {
		fmt.Fprintf(&sb, "(deny file-write* (subpath %q))\n", d)
		fmt.Fprintf(&sb, "(deny file-read* (subpath %q))\n", d)
	}
	for _, d := range sortedPaths(p.ReadOnly) {
		fmt.Fprintf(&sb, "(allow file-read* (subpath %q))\n", d)
	}
	for _, d := range sortedPaths(p.ReadWrite) {
		fmt.Fprintf(&sb, "(allow file-read* (subpath %q))\n", d)
		fmt.Fprintf(&sb, "(allow file-write* (subpath %q))\n", d)
	}
	sb.WriteString("; End SIN-Code profile.\n")
	return sb.String()
}

func sortedPaths(in []string) []string {
	out := make([]string, len(in))
	copy(out, in)
	sort.Strings(out)
	return out
}

// Exec runs `cmd` with the Seatbelt policy applied. Sandbox-exec is
// expected on PATH; if it returns an error the typed ErrSeatbeltDenied
// is surfaced (or the wrapped exec error).
func (b SeatbeltBackend) Exec(ctx context.Context, cmd *exec.Cmd, workdir string) error {
	if _, err := exec.LookPath("sandbox-exec"); err != nil {
		return fmt.Errorf("sandbox: sandbox-exec not on PATH: %w", err)
	}
	policy := b.Policy.Profile()
	// Build sandbox-exec invocation that wraps the user's cmd.
	wrapped := exec.CommandContext(ctx, "sandbox-exec", "-p", policy)
	wrapped.Path = "/usr/bin/sandbox-exec" // pin to known location
	wrapped.Args = append([]string{"sandbox-exec", "-p", policy}, cmd.Args...)
	if cmd.Dir != "" {
		wrapped.Dir = cmd.Dir
	} else {
		wrapped.Dir = workdir
	}
	wrapped.Stdin = cmd.Stdin
	wrapped.Stdout = cmd.Stdout
	wrapped.Env = cmd.Env
	var stderrBuf bytes.Buffer
	switch v := cmd.Stderr.(type) {
	case nil:
		wrapped.Stderr = &stderrBuf
	default:
		wrapped.Stderr = &teeWriter{v, &stderrBuf}
	}
	if err := wrapped.Run(); err != nil {
		// Sandbox-exec signals "deny" via exit 71. We surface that
		// distinctly so callers can retry under a relaxed policy.
		if exitErr, ok := err.(*exec.ExitError); ok {
			if exitErr.ExitCode() == 71 || strings.Contains(stderrBuf.String(), "deny") {
				return fmt.Errorf("%w: %s", ErrSeatbeltDenied, strings.TrimSpace(stderrBuf.String()))
			}
		}
		return fmt.Errorf("sandbox: seatbelt exec: %w", err)
	}
	return nil
}

// teeWriter splits Write calls across two writers.
type teeWriter struct {
	a, b interface {
		Write(p []byte) (int, error)
	}
}

func (t *teeWriter) Write(p []byte) (int, error) {
	t.a.Write(p)
	return t.b.Write(p)
}
