"""Generate .opencode hooks for automatic SIN-Brain calls.

Purpose: Installs pre- and post-command shell hooks into ~/.opencode/hooks/ so
that every opencode run transparently recalls context before the agent starts
and remembers results after the agent finishes.

Docs: hooks.doc.md
"""
from __future__ import annotations

import os
from pathlib import Path

# Default brain storage path (relative to repo root or absolute).
_DEFAULT_BRAIN_PATH = os.getenv("SIN_BRAIN_PATH", ".sin/brain.db")

# Hook templates use defensive `command -v` checks so the hooks are harmless
# when sin-brain is not installed.

_PRE_COMMAND_TEMPLATE = r"""#!/bin/bash
# SIN-Brain pre-command hook — auto-recalls context before every opencode command.
# Auto-generated by `sin hooks-install`. Do NOT edit manually.

# ---------------------------------------------------------------------------
# 1. Detect the current task context
# ---------------------------------------------------------------------------
# opencode does not expose the task prompt via env, but agents often set
# OPENCODE_TASK when running in CI/automation. Fall back to the current
# working directory name as a minimal context signal.
TASK="${OPENCODE_TASK:-$(basename "$PWD")}"

# ---------------------------------------------------------------------------
# 2. Recall relevant memories from SIN-Brain (defensive — sin-brain optional)
# ---------------------------------------------------------------------------
if command -v sin-brain &> /dev/null; then
    # Recall up to 3 memories scoped to the current task.
    # We write JSON to a temp file and then pretty-print the content lines
    # so the agent can see the context inline in the terminal output.
    TMP_CTX=$(mktemp /tmp/sin_brain_context.XXXXXX.json)
    if sin-brain recall "$TASK" --limit 3 --format json > "$TMP_CTX" 2>/dev/null; then
        # Extract memory contents with jq if available, otherwise grep.
        if command -v jq &> /dev/null; then
            CONTEXT=$(jq -r '.memories[]?.content // empty' "$TMP_CTX" 2>/dev/null)
        else
            CONTEXT=$(grep -o '"content": *"[^"]*"' "$TMP_CTX" | sed 's/"content": *"//;s/"$//' | head -n 3)
        fi
        if [ -n "$CONTEXT" ]; then
            echo "[SIN-Brain] Recalled context for task: $TASK"
            echo "$CONTEXT"
            # Export for child processes (agent can read $SIN_BRAIN_CONTEXT).
            export SIN_BRAIN_CONTEXT="$CONTEXT"
        fi
    fi
    rm -f "$TMP_CTX"
fi

# ---------------------------------------------------------------------------
# 3. Legacy: also read /tmp/brain_context.json if present (backwards compat)
# ---------------------------------------------------------------------------
if [ -f /tmp/brain_context.json ]; then
    export BRAIN_CONTEXT=$(cat /tmp/brain_context.json)
fi
"""

_POST_COMMAND_TEMPLATE = r"""#!/bin/bash
# SIN-Brain post-command hook — auto-remembers results after every opencode command.
# Auto-generated by `sin hooks-install`. Do NOT edit manually.

# ---------------------------------------------------------------------------
# 1. Gather the last command result
# ---------------------------------------------------------------------------
# Agents can write a summary to /tmp/last_task_result.txt before exiting.
# If that file exists, we persist it as an episodic memory.
RESULT_FILE="/tmp/last_task_result.txt"
TASK="${OPENCODE_TASK:-$(basename "$PWD")}"

if [ -f "$RESULT_FILE" ]; then
    RESULT=$(cat "$RESULT_FILE")
    if [ -n "$RESULT" ]; then
        # -------------------------------------------------------------------
        # 2. Remember in SIN-Brain (defensive — sin-brain optional)
        # -------------------------------------------------------------------
        if command -v sin-brain &> /dev/null; then
            # Store as episodic memory with the task as context.
            if sin-brain remember "$RESULT" --kind "task" --tier "episodic" --context "$TASK" 2>/dev/null; then
                echo "[SIN-Brain] Remembered task result for: $TASK"
            else
                # Fallback: write to a local queue for later ingestion.
                echo "$RESULT" >> "${SIN_BRAIN_QUEUE:-.sin/brain_queue.txt}"
            fi
        fi
    fi
    # Clean up so the next run does not re-remember the same result.
    rm -f "$RESULT_FILE"
fi

# ---------------------------------------------------------------------------
# 3. Legacy: also remember from /tmp/last_command_result.json (backwards compat)
# ---------------------------------------------------------------------------
if [ -f /tmp/last_command_result.json ]; then
    LEGACY_RESULT=$(cat /tmp/last_command_result.json)
    if command -v sin-brain &> /dev/null && [ -n "$LEGACY_RESULT" ]; then
        sin-brain remember "Task completed: $TASK" --kind "episodic" --context "$LEGACY_RESULT" 2>/dev/null || true
    fi
    rm -f /tmp/last_command_result.json
fi
"""


def install_opencode_hooks(
    pre_command: bool = True,
    post_command: bool = True,
    brain_path: str = _DEFAULT_BRAIN_PATH,
) -> list[str]:
    """Install SIN-Brain hooks into ~/.opencode/hooks/.

    Args:
        pre_command: Install the pre-command hook that recalls context.
        post_command: Install the post-command hook that remembers results.
        brain_path: Path to the SIN-Brain database (used as a comment in the
            hook for reference; the actual brain path is resolved by the
            sin-brain CLI at runtime).

    Returns:
        A list of absolute paths to the installed hook files.
    """
    hooks_dir = Path.home() / ".opencode" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    installed: list[str] = []

    if pre_command:
        pre_hook = hooks_dir / "pre-command.sh"
        # Write the template with the brain path as a comment for documentation.
        content = _PRE_COMMAND_TEMPLATE.replace(
            "# Auto-generated by `sin hooks-install`.",
            f"# Auto-generated by `sin hooks-install` (brain_path={brain_path}).",
        )
        pre_hook.write_text(content, encoding="utf-8")
        pre_hook.chmod(0o755)
        installed.append(str(pre_hook))

    if post_command:
        post_hook = hooks_dir / "post-command.sh"
        content = _POST_COMMAND_TEMPLATE.replace(
            "# Auto-generated by `sin hooks-install`.",
            f"# Auto-generated by `sin hooks-install` (brain_path={brain_path}).",
        )
        post_hook.write_text(content, encoding="utf-8")
        post_hook.chmod(0o755)
        installed.append(str(post_hook))

    return installed


def uninstall_opencode_hooks() -> list[str]:
    """Remove SIN-Brain hooks from ~/.opencode/hooks/.

    Returns:
        A list of absolute paths to the removed hook files.
    """
    hooks_dir = Path.home() / ".opencode" / "hooks"
    removed: list[str] = []

    for name in ("pre-command.sh", "post-command.sh"):
        hook = hooks_dir / name
        if hook.exists():
            hook.unlink()
            removed.append(str(hook))

    return removed


def list_opencode_hooks() -> list[str]:
    """List installed SIN-Brain hooks in ~/.opencode/hooks/.

    Returns:
        A list of absolute paths to existing hook files.
    """
    hooks_dir = Path.home() / ".opencode" / "hooks"
    found: list[str] = []

    for name in ("pre-command.sh", "post-command.sh"):
        hook = hooks_dir / name
        if hook.exists():
            found.append(str(hook))

    return found
