// SPDX-License-Identifier: MIT
// Purpose: tests for the spec↔code signature drift checker. Builds a
// temp Go source tree, parses it with go/parser, and checks that
// matching / non-matching signatures are reported correctly.
// Docs: docs/SPEC-LAYER.md §"Drift detection (the hardening)"
package spec

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeGoFile is a tiny helper that writes a Go file under dir/name.
func writeGoFile(t *testing.T, dir, name, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestDrift_AllMatch(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "a.go", `package x

func Foo(x int, y string) error { return nil }
func Bar()                     {}
`)

	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "`Foo(x int, y string) error` is in the public API", Priority: Must},
			{ID: "R2", Text: "`Bar()` is in the public API", Priority: Must},
		},
	}
	rep, err := s.DetectSignatureDrift(root)
	if err != nil {
		t.Fatalf("DetectSignatureDrift: %v", err)
	}
	if len(rep.Hits) != 2 {
		t.Fatalf("expected 2 hits, got %d", len(rep.Hits))
	}
	for _, h := range rep.Hits {
		if !h.Match {
			t.Errorf("%s: expected match, got drift: %s", h.RequirementID, h.Note)
		}
	}
	if rep.HasFailures() {
		t.Fatal("HasFailures should be false")
	}
}

func TestDrift_ParamMismatch(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "a.go", `package x

func Foo(x int) error { return nil }
`)

	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "`Foo(x string) error` is in the public API", Priority: Must},
		},
	}
	rep, _ := s.DetectSignatureDrift(root)
	if len(rep.Hits) != 1 {
		t.Fatalf("expected 1 hit, got %d", len(rep.Hits))
	}
	if rep.Hits[0].Match {
		t.Fatal("expected drift (param type differs)")
	}
	if !strings.Contains(rep.Hits[0].Note, "drift") {
		t.Fatalf("expected drift note, got: %q", rep.Hits[0].Note)
	}
	if !rep.HasFailures() {
		t.Fatal("HasFailures should be true")
	}
}

func TestDrift_FunctionMissing(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "a.go", `package x

func Other() {}
`)

	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "`Foo() error` is in the public API", Priority: Must},
		},
	}
	rep, _ := s.DetectSignatureDrift(root)
	if len(rep.Hits) != 1 {
		t.Fatalf("expected 1 hit, got %d", len(rep.Hits))
	}
	if rep.Hits[0].Match {
		t.Fatal("expected drift (function missing)")
	}
	if !strings.Contains(rep.Hits[0].Note, "not found") {
		t.Fatalf("expected 'not found' note, got: %q", rep.Hits[0].Note)
	}
}

func TestDrift_NoSignaturesInSpec(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "a.go", `package x

func Foo() {}
`)

	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "the system is well-tested", Priority: Must},
			{ID: "R2", Text: "documentation is up to date", Priority: Must},
		},
	}
	rep, err := s.DetectSignatureDrift(root)
	if err != nil {
		t.Fatalf("DetectSignatureDrift: %v", err)
	}
	if len(rep.Hits) != 0 {
		t.Fatalf("expected 0 hits, got %d", len(rep.Hits))
	}
	if rep.HasFailures() {
		t.Fatal("HasFailures should be false (no signatures = no drift)")
	}
}

func TestDrift_MethodAndTestFilesSkipped(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "real.go", `package x

func Public() {}
`)
	// Methods on receivers: PR 4 supports them via the qualified
	// `Type.Method` lookup. The spec uses the same qualifier.
	writeGoFile(t, root, "method.go", `package x

type S struct{}
func (S) Method() {}
`)
	// Test files: must be skipped.
	writeGoFile(t, root, "real_test.go", `package x

func TestThing() {}
`)
	// Generated files: must be skipped (filename prefix + content marker).
	writeGoFile(t, root, "zz_generated.go", `// Code generated by tool. DO NOT EDIT.

package x

func AutoGen() {}
`)

	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "`Public()` is in the public API", Priority: Must},
			// PR 4: methods are addressed via "Receiver.Method".
			{ID: "R2", Text: "`S.Method()` is in the public API", Priority: Must},
			{ID: "R3", Text: "`TestThing()` is in the public API", Priority: Must},
			{ID: "R4", Text: "`AutoGen()` is in the public API", Priority: Must},
		},
	}
	rep, _ := s.DetectSignatureDrift(root)
	// R1 + R2 match. R3 (test) + R4 (generated) are skipped.
	if len(rep.Hits) != 4 {
		t.Fatalf("expected 4 hits, got %d", len(rep.Hits))
	}
	if !rep.Hits[0].Match {
		t.Errorf("R1 should match: %s", rep.Hits[0].Note)
	}
	if !rep.Hits[1].Match {
		t.Errorf("R2 (method) should now match in PR 4: %s", rep.Hits[1].Note)
	}
	if rep.Hits[2].Match {
		t.Error("R3 (test file) should NOT match")
	}
	if rep.Hits[3].Match {
		t.Error("R4 (generated file) should NOT match")
	}
}

func TestDrift_WhitespaceTolerant(t *testing.T) {
	root := t.TempDir()
	writeGoFile(t, root, "a.go", `package x

func Foo(x int, y int) error { return nil }
`)

	// Spec has extra spaces between params; should still match.
	s := &Spec{
		Title: "demo",
		Requirements: []Requirement{
			{ID: "R1", Text: "`Foo(x  int,   y int)   error` is in the public API", Priority: Must},
		},
	}
	rep, _ := s.DetectSignatureDrift(root)
	if len(rep.Hits) != 1 {
		t.Fatalf("expected 1 hit, got %d", len(rep.Hits))
	}
	if !rep.Hits[0].Match {
		t.Fatalf("expected whitespace-tolerant match, got drift: %s", rep.Hits[0].Note)
	}
}
