// SPDX-License-Identifier: MIT
// Purpose: minimal filesystem walker used by spec/drift.go to find Go
// source files. Kept inline (instead of using cmd/sin-code/internal/
// walk) so the spec package has zero non-stdlib deps.
// Docs: docs/SPEC-LAYER.md §"Drift detection (the hardening)"
package spec

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

func walkGo(root string, fn func(path string)) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil // skip directories we can't read
		}
		if d.IsDir() {
			// Skip vendor, .git, and dotfile trees.
			name := d.Name()
			if name == "vendor" || name == ".git" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// Skip test files and auto-generated files for the v0 check.
		base := filepath.Base(path)
		if strings.HasSuffix(base, "_test.go") {
			return nil
		}
		if strings.HasPrefix(base, "zz_generated_") {
			return nil
		}
		// Best-effort: skip files whose first line is a generated marker.
		if isGenerated(path) {
			return nil
		}
		fn(path)
		return nil
	})
}

func isGenerated(path string) bool {
	f, err := os.Open(path) // #nosec G304 (caller-controlled path)
	if err != nil {
		return false
	}
	defer f.Close()
	buf := make([]byte, 256)
	n, _ := f.Read(buf)
	return strings.Contains(string(buf[:n]), "Code generated by")
}
