// SPDX-License-Identifier: MIT
// Purpose: Test generation engine for SIN-Code chat tools. Generates
// table-driven Go tests from source files, either by shelling out to
// gotests (if available on PATH) or by a pure-stdlib fallback that uses
// go/parser to build minimal test scaffolding. The result is verified
// by running go test on the generated code.
//
// This is the Phase 1 prototype for the Test-First Verify-Loop (RFC-test-automation.md).
// sin-debt: medium, upgrade: add LLM case filling in Phase 2
package testgen

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"
)

const (
	// DefaultTimeout is the hard ceiling for a generate-and-verify cycle.
	DefaultTimeout = 2 * time.Minute

	// GeneratedMarker is inserted into every generated file so follow-up
	// runs can detect SIN-Code-generated tests.
	GeneratedMarker = "// Code generated by sin_test_generate. DO NOT EDIT."
)

// Options controls what to generate and how to verify it.
type Options struct {
	// File is a single .go file path. If empty, Package is used.
	File string

	// Package is a package pattern such as "./internal/foo" or "./...".
	// Only used when File is empty.
	Package string

	// UseLLM, when non-nil, fills TODO cases with realistic inputs.
	// If nil, generated tests contain table-driven scaffolding with TODO cases.
	UseLLM func(ctx context.Context, code string) (string, error)

	// Overwrite allows replacing an existing generated test file.
	Overwrite bool

	// Timeout caps the generate + verify cycle.
	Timeout time.Duration

	// Cases, when present, is spliced into the generated test instead of
	// the basic-case scaffold. Key is the function name (possibly with
	// receiver prefix). Functions without an entry fall back to the
	// zero-value scaffold.
	Cases map[string][]TestCase

	// MaxRepairIters bounds the generate/execute/repair loop. 0 disables
	// repair; default is 3. After each compile or test failure, the LLM
	// is re-prompted with the failing output up to (max - 1) additional
	// times.
	MaxRepairIters int
}

// Result reports what was generated and whether it compiles.
type Result struct {
	GeneratedFiles []string `json:"generated_files"`
	TestOutput       string   `json:"test_output"`
	TestPassed       bool     `json:"test_passed"`
	Error            string   `json:"error,omitempty"`
}

// Generate creates test scaffolding for the target file or package.
// It returns the list of generated files and a verification report.
func Generate(ctx context.Context, opts Options) Result {
	if opts.Timeout <= 0 {
		opts.Timeout = DefaultTimeout
	}
	cctx, cancel := context.WithTimeout(ctx, opts.Timeout)
	defer cancel()

	if opts.File != "" {
		return generateForFile(cctx, opts)
	}
	return generateForPackage(cctx, opts)
}

func generateForFile(ctx context.Context, opts Options) Result {
	file := opts.File
	if !strings.HasSuffix(file, ".go") || strings.HasSuffix(file, "_test.go") {
		return Result{Error: fmt.Sprintf("target must be a non-test .go file: %s", file)}
	}

	outFile := deriveTestFileName(file)

	if !opts.Overwrite && fileExists(outFile) {
		return Result{Error: fmt.Sprintf("test file already exists: %s (use overwrite=true)", outFile)}
	}

	var gen []string
	if hasGotests() {
		if err := runGotests(ctx, file, outFile); err != nil {
			return Result{Error: fmt.Sprintf("gotests failed: %v", err)}
		}
		gen = append(gen, outFile)
	} else {
		// Fallback: parse file and emit minimal table-driven scaffolding.
		code, err := generateFallback(ctx, file, opts.UseLLM, opts.Cases)
		if err != nil {
			return Result{Error: fmt.Sprintf("fallback generation failed: %v", err)}
		}
		if err := os.WriteFile(outFile, []byte(code), 0o644); err != nil {
			return Result{Error: fmt.Sprintf("write test file: %v", err)}
		}
		gen = append(gen, outFile)
	}

	// Verify generated tests compile and run.
	pkg := filepath.Dir(file)
	if pkg == "" || pkg == "." {
		pkg = "./"
	}
	out, passed := runGoTest(ctx, pkg)

	return Result{
		GeneratedFiles: gen,
		TestOutput:     out,
		TestPassed:     passed,
	}
}

func generateForPackage(ctx context.Context, opts Options) Result {
	pkg := opts.Package
	if pkg == "" {
		pkg = "./..."
	}

	if hasGotests() {
		out, err := runGotestsPackage(ctx, pkg)
		if err != nil {
			return Result{Error: fmt.Sprintf("gotests package failed: %v\n%s", err, out)}
		}
		testOut, passed := runGoTest(ctx, pkg)
		return Result{
			GeneratedFiles: detectGeneratedFiles(pkg),
			TestOutput:     testOut,
			TestPassed:     passed,
		}
	}

	// Fallback: enumerate .go files and generate for each.
	files, err := findGoFiles(pkg)
	if err != nil {
		return Result{Error: fmt.Sprintf("find go files: %v", err)}
	}

	var generated []string
	for _, f := range files {
		res := generateForFile(ctx, Options{
			File:         f,
			UseLLM:       opts.UseLLM,
			Overwrite:    opts.Overwrite,
			Timeout:      opts.Timeout,
			Cases:        opts.Cases,
			MaxRepairIters: opts.MaxRepairIters,
		})
		if res.Error != "" {
			return res
		}
		generated = append(generated, res.GeneratedFiles...)
	}

	pkgDir := "./..."
	if pkg != "./..." {
		pkgDir = pkg
	}
	out, passed := runGoTest(ctx, pkgDir)

	return Result{
		GeneratedFiles: generated,
		TestOutput:     out,
		TestPassed:     passed,
	}
}

func hasGotests() bool {
	_, err := exec.LookPath("gotests")
	return err == nil
}

func runGotests(ctx context.Context, file, outFile string) error {
	// gotests -all -w writes to <file>_test.go
	cmd := exec.CommandContext(ctx, "gotests", "-all", "-w", file)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	// Ensure marker is present.
	return prependMarkerIfMissing(deriveTestFileName(file))
}

func runGotestsPackage(ctx context.Context, pkg string) (string, error) {
	cmd := exec.CommandContext(ctx, "gotests", "-all", "-w", pkg)
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func runGoTest(ctx context.Context, pkg string) (string, bool) {
	cmd := exec.CommandContext(ctx, "go", "test", "-count=1", "-timeout=60s", pkg)
	out, err := cmd.CombinedOutput()
	return string(out), err == nil
}

func deriveTestFileName(file string) string {
	if strings.HasSuffix(file, "_test.go") {
		return file
	}
	return strings.TrimSuffix(file, ".go") + "_test.go"
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func prependMarkerIfMissing(p string) error {
	data, err := os.ReadFile(p)
	if err != nil {
		return err
	}
	if strings.Contains(string(data), GeneratedMarker) {
		return nil
	}
	out := []byte(GeneratedMarker + "\n\n" + string(data))
	return os.WriteFile(p, out, 0o644)
}

func detectGeneratedFiles(pkg string) []string {
	// Best-effort: collect *_test.go that contain the marker.
	var out []string
	err := filepath.WalkDir(pkg, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, "_test.go") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		if strings.Contains(string(data), GeneratedMarker) {
			out = append(out, path)
		}
		return nil
	})
	_ = err
	return out
}

func findGoFiles(pkg string) ([]string, error) {
	var files []string
	dir := pkg
	if strings.HasSuffix(dir, "/...") {
		dir = strings.TrimSuffix(dir, "/...")
	}
	if dir == "" || dir == "./" || dir == "." {
		dir = "."
	}
	recursive := strings.HasSuffix(pkg, "/...")

	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if !recursive && path != dir {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

// generateFallback produces a minimal table-driven test from a Go source file
// without requiring gotests. It targets exported functions with simple
// signatures; LLM-supplied cases (in cases) are spliced into the table
// when a matching entry exists. Functions missing an entry fall back to
// the zero-value scaffold.
func generateFallback(ctx context.Context, file string, llm func(context.Context, string) (string, error), cases map[string][]TestCase) (string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
	if err != nil {
		return "", err
	}

	pkgName := f.Name.Name

	var funcs []FuncInfo
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !ast.IsExported(fn.Name.Name) {
			continue
		}
		funcs = append(funcs, describeFunc(fn))
	}

	if len(funcs) == 0 {
		return "", fmt.Errorf("no exported functions found in %s", file)
	}
	if cases == nil {
		cases = map[string][]TestCase{}
	}

	data := struct {
		Package string
		Marker  string
		Funcs   []FuncInfo
		Cases   map[string][]TestCase
		HasLLM  bool
	}{
		Package: pkgName,
		Marker:  GeneratedMarker,
		Funcs:   funcs,
		Cases:   cases,
		HasLLM:  llm != nil,
	}

	var buf bytes.Buffer
	if err := fallbackTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// FuncInfo is a minimal description of a Go function for template rendering.
type FuncInfo struct {
	Name       string
	Args       []Param
	Returns    []Param
	IsMethod   bool
	Receiver   string
	HasError   bool
}

type Param struct {
	Name string
	Type string
}

func describeFunc(fn *ast.FuncDecl) FuncInfo {
	info := FuncInfo{Name: fn.Name.Name}
	if fn.Recv != nil && len(fn.Recv.List) > 0 {
		info.IsMethod = true
		info.Receiver = exprToString(fn.Recv.List[0].Type)
	}
	for _, p := range fn.Type.Params.List {
		typ := exprToString(p.Type)
		for _, n := range p.Names {
			info.Args = append(info.Args, Param{Name: n.Name, Type: typ})
		}
		if len(p.Names) == 0 {
			info.Args = append(info.Args, Param{Name: "arg", Type: typ})
		}
	}
	if fn.Type.Results != nil {
		for _, r := range fn.Type.Results.List {
			typ := exprToString(r.Type)
			if typ == "error" {
				info.HasError = true
			}
			for _, n := range r.Names {
				info.Returns = append(info.Returns, Param{Name: n.Name, Type: typ})
			}
			if len(r.Names) == 0 {
				info.Returns = append(info.Returns, Param{Name: "got", Type: typ})
			}
		}
	}
	return info
}

func exprToString(expr ast.Expr) string {
	switch v := expr.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + exprToString(v.X)
	case *ast.ArrayType:
		return "[]" + exprToString(v.Elt)
	case *ast.MapType:
		return "map[" + exprToString(v.Key) + "]" + exprToString(v.Value)
	case *ast.SelectorExpr:
		return exprToString(v.X) + "." + v.Sel.Name
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.FuncType:
		return "func"
	case *ast.ChanType:
		return "chan"
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func simpleType(t string) bool {
	switch t {
	case "int", "int64", "int32", "string", "bool", "float64", "float32", "uint", "uint64":
		return true
	}
	return false
}

func zeroValue(t string) string {
	switch t {
	case "int", "int64", "int32", "uint", "uint64":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	case "float64", "float32":
		return "0.0"
	default:
		return "nil"
	}
}

// jsonLiteral renders a JSON-decoded value as a Go struct/array/map
// literal. Supported types: nil, bool, float64, int, string, []any,
// map[string]any. Unsupported types fall back to nil so a bad field
// never breaks the entire generated test.
func jsonLiteral(v any) string {
	switch x := v.(type) {
	case nil:
		return "nil"
	case bool:
		if x {
			return "true"
		}
		return "false"
	case float64:
		// JSON numbers decode as float64. Try integer form first so the
		// common case emits `2` instead of `2.0`.
		if float64(int(x)) == x {
			return fmt.Sprintf("%d", int(x))
		}
		return fmt.Sprintf("%v", x)
	case float32:
		return fmt.Sprintf("%v", x)
	case int:
		return fmt.Sprintf("%d", x)
	case int64:
		return fmt.Sprintf("%d", x)
	case string:
		return fmt.Sprintf("%q", x)
	case []any:
		parts := make([]string, 0, len(x))
		for _, e := range x {
			parts = append(parts, jsonLiteral(e))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		keys := make([]string, 0, len(x))
		for k := range x {
			keys = append(keys, k)
		}
		// Stable order so the generated test is byte-stable.
		sort.Strings(keys)
		parts := make([]string, 0, len(x))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%q: %s", k, jsonLiteral(x[k])))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		return "nil"
	}
}

// testKey is the map key used to look up per-function LLM cases. It
// matches both method (`Receiver_Name`) and free-function (`Name`)
// spellings of describeFunc output.
func testKey(fn FuncInfo) string {
	if fn.IsMethod {
		return fn.Receiver + "_" + fn.Name
	}
	return fn.Name
}

// FunctionsFromSource is a public parser entry point so the chat tool
// can ask the LLM for cases for every exported function in a source
// file without re-implementing describeFunc in caller code.
func FunctionsFromSource(file string) ([]FuncInfo, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var out []FuncInfo
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !ast.IsExported(fn.Name.Name) {
			continue
		}
		out = append(out, describeFunc(fn))
	}
	return out, nil
}

// renderCaseRow writes one `tests := []struct{...}{...}` element for
// the LLM-supplied TestCase. Unknown arg names or want names produce a
// zero-value fallback so the partial row still compiles.
func renderCaseRow(fn FuncInfo, tc TestCase) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\t\t{\n")
	fmt.Fprintf(&b, "\t\t\tname: %q,\n", tc.Name)
	if len(fn.Args) > 0 {
		fmt.Fprintf(&b, "\t\t\targs: args{\n")
		for _, a := range fn.Args {
			if v, ok := tc.Args[a.Name]; ok {
				fmt.Fprintf(&b, "\t\t\t\t%s: %s,\n", a.Name, jsonLiteral(v))
			} else {
				fmt.Fprintf(&b, "\t\t\t\t%s: %s,\n", a.Name, zeroValue(a.Type))
			}
		}
		fmt.Fprintf(&b, "\t\t\t},\n")
	}
	for _, r := range fn.Returns {
		// Skip the `error` slot — it is encoded via WantErr.
		if r.Type == "error" {
			continue
		}
		// Convention: want<returnedName> (matches existing template).
		field := "want" + strings.Title(r.Name)
		if v, ok := tc.Wants[r.Name]; ok {
			fmt.Fprintf(&b, "\t\t\t%s: %s,\n", field, jsonLiteral(v))
		} else {
			fmt.Fprintf(&b, "\t\t\t%s: %s,\n", field, zeroValue(r.Type))
		}
	}
	fmt.Fprintf(&b, "\t\t\twantErr: %v,\n", tc.WantErr)
	fmt.Fprintf(&b, "\t\t},\n")
	return b.String()
}

var fallbackTemplate = template.Must(template.New("test").Funcs(template.FuncMap{
	"simpleType": simpleType,
	"zeroValue":  zeroValue,
	"joinArgs": func(args []Param) string {
		var parts []string
		for _, a := range args {
			parts = append(parts, a.Name)
		}
		return strings.Join(parts, ", ")
	},
	"joinArgsTyped": func(args []Param) string {
		var parts []string
		for _, a := range args {
			parts = append(parts, fmt.Sprintf("%s %s", a.Name, a.Type))
		}
		return strings.Join(parts, ", ")
	},
	"hasCasesFor": func(fn FuncInfo, cases map[string][]TestCase) bool {
		_, ok := cases[testKey(fn)]
		return ok
	},
	"casesFor": func(fn FuncInfo, cases map[string][]TestCase) []TestCase {
		return cases[testKey(fn)]
	},
	"renderCase": func(fn FuncInfo, tc TestCase) string {
		return renderCaseRow(fn, tc)
	},
	"joinReturns": func(rets []Param) string {
		var parts []string
		for _, r := range rets {
			parts = append(parts, r.Name)
		}
		return strings.Join(parts, ", ")
	},
	"returnTypes": func(rets []Param) string {
		var parts []string
		for _, r := range rets {
			parts = append(parts, r.Type)
		}
		if len(parts) == 1 {
			return parts[0]
		}
		return "(" + strings.Join(parts, ", ") + ")"
	},
}).Parse(`{{ .Marker }}
package {{ .Package }}

import "testing"

{{ range .Funcs }}{{ $fn := . }}
func Test{{ if .IsMethod }}{{ .Receiver }}_{{ end }}{{ .Name }}(t *testing.T) {
	type args struct {
		{{ range .Args }}{{ .Name }} {{ .Type }}
		{{ end }}
	}
	tests := []struct {
		name string
		args args
		{{ range .Returns }}want{{ .Name }} {{ .Type }}
		{{ end }}wantErr bool
	}{
		{{ if hasCasesFor . $.Cases }}{{ range (casesFor . $.Cases) }}{{ renderCase $fn . }}
		{{ end }}{{ else }}
		{
			name: "basic case",
			{{ if .Args }}args: args{
				{{ range .Args }}{{ .Name }}: {{ zeroValue .Type }},
				{{ end }}
			},{{ end }}
			{{ range .Returns }}want{{ .Name }}: {{ zeroValue .Type }},
			{{ end }}wantErr: false,
		},
		{{ end }}
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			{{ if .IsMethod }}{{ .Receiver }}{{ else }}{{ end }}{{ if .Returns }}got{{ range .Returns }}{{ .Name }}{{ end }} := {{ end }}{{ .Name }}({{ joinArgs .Args }})
			{{ if .HasError }}if (err != nil) != tt.wantErr {
				t.Errorf("{{ .Name }}() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			{{ end }}
			{{ range .Returns }}{{ if ne .Type "error" }}if got{{ .Name }} != tt.want{{ .Name }} {
				t.Errorf("{{ $fn.Name }}() = %v, want %v", got{{ .Name }}, tt.want{{ .Name }})
			}
			{{ end }}{{ end }}
		})
	}
}
{{ end }}
`))
