// SPDX-License-Identifier: MIT
// Purpose: Test generation engine for SIN-Code chat tools. Generates
// table-driven Go tests from source files, either by shelling out to
// gotests (if available on PATH) or by a pure-stdlib fallback that uses
// go/parser to build minimal test scaffolding. The result is verified
// by running go test on the generated code.
//
// Test-First Verify-Loop implementation (RFC-test-automation.md), including
// LLM-driven case filling and repair via Options.UseLLM.
package testgen

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/OpenSIN-Code/SIN-Code/cmd/sin-code/internal/filemode"
)

const (
	// DefaultTimeout is the hard ceiling for a generate-and-verify cycle.
	DefaultTimeout = 2 * time.Minute

	// GeneratedMarker is inserted into every generated file so follow-up
	// runs can detect SIN-Code-generated tests.
	GeneratedMarker = "// Code generated by sin_test_generate. DO NOT EDIT."
)

// Options controls what to generate and how to verify it.
type Options struct {
	// File is a single .go file path. If empty, Package is used.
	File string

	// Package is a package pattern such as "./internal/foo" or "./...".
	// Only used when File is empty.
	Package string

	// UseLLM, when non-nil, fills TODO cases with realistic inputs.
	// If nil, generated tests contain table-driven scaffolding with TODO cases.
	UseLLM func(ctx context.Context, code string) (string, error)

	// Overwrite allows replacing an existing generated test file.
	Overwrite bool

	// Timeout caps the generate + verify cycle.
	Timeout time.Duration

	// Cases, when present, is spliced into the generated test instead of
	// the basic-case scaffold. Key is the function name (possibly with
	// receiver prefix). Functions without an entry fall back to the
	// zero-value scaffold.
	Cases map[string][]TestCase

	// MaxRepairIters bounds the generate/execute/repair loop. 0 disables
	// repair; default is 3. After each compile or test failure, the LLM
	// is re-prompted with the failing output up to (max - 1) additional
	// times.
	MaxRepairIters int
}

// Result reports what was generated and whether it compiles.
type Result struct {
	GeneratedFiles []string `json:"generated_files"`
	TestOutput     string   `json:"test_output"`
	TestPassed     bool     `json:"test_passed"`
	Error          string   `json:"error,omitempty"`
}

// Generate creates test scaffolding for the target file or package.
// It returns the list of generated files and a verification report.
func Generate(ctx context.Context, opts Options) Result {
	if opts.Timeout <= 0 {
		opts.Timeout = DefaultTimeout
	}
	cctx, cancel := context.WithTimeout(ctx, opts.Timeout)
	defer cancel()

	if opts.File != "" {
		return generateForFile(cctx, opts)
	}
	return generateForPackage(cctx, opts)
}

func generateForFile(ctx context.Context, opts Options) Result {
	file := opts.File
	if !strings.HasSuffix(file, ".go") || strings.HasSuffix(file, "_test.go") {
		return Result{Error: fmt.Sprintf("target must be a non-test .go file: %s", file)}
	}

	outFile := deriveTestFileName(file)

	if !opts.Overwrite && fileExists(outFile) {
		return Result{Error: fmt.Sprintf("test file already exists: %s (use overwrite=true)", outFile)}
	}

	maxIters := opts.MaxRepairIters
	if maxIters <= 0 {
		maxIters = 1
	}
	if maxIters > 10 {
		maxIters = 10 // safety cap so a misconfigured caller cannot pin the loop
	}

	// Must run with a fallback path (no gotests on PATH) for repairs.
	skipFallback := hasGotests()

	// Accumulate per-iteration test output so callers can see the
	// attempt history on failure.
	var outputs []string
	gen := []string{outFile}
	casesMap := opts.Cases // gets rebuilt on each repair iteration
	for attempt := 1; attempt <= maxIters; attempt++ {
		if skipFallback {
			if err := runGotests(ctx, file, outFile); err != nil {
				return Result{
					GeneratedFiles: gen,
					TestOutput:     joinAttemptOutputs(outputs),
					Error:          fmt.Sprintf("gotests failed (attempt %d): %v", attempt, err),
				}
			}
		} else {
			// Fallback: parse file and emit minimal table-driven scaffolding.
			code, err := generateFallback(ctx, file, opts.UseLLM, casesMap)
			if err != nil {
				return Result{
					GeneratedFiles: gen,
					TestOutput:     joinAttemptOutputs(outputs),
					Error:          fmt.Sprintf("fallback generation failed (attempt %d): %v", attempt, err),
				}
			}
			if err := os.WriteFile(outFile, []byte(code), filemode.Default()); err != nil {
				return Result{
					GeneratedFiles: gen,
					TestOutput:     joinAttemptOutputs(outputs),
					Error:          fmt.Sprintf("write test file (attempt %d): %v", attempt, err),
				}
			}
		}

		// Verify generated tests compile and run.
		pkg := filepath.Dir(file)
		if pkg == "" || pkg == "." {
			pkg = "./"
		}
		out, passed := runGoTest(ctx, pkg)
		outputs = append(outputs, fmt.Sprintf("--- attempt %d ---\n%s", attempt, out))
		if passed {
			return Result{
				GeneratedFiles: gen,
				TestOutput:     joinAttemptOutputs(outputs),
				TestPassed:     true,
			}
		}
		// Loop budget exhausted -> give up.
		if attempt >= maxIters {
			break
		}
		// Only retry when UseLLM is wired: without an LLM there is
		// nothing to repair against.
		if opts.UseLLM == nil {
			break
		}
		// Ask the LLM to repair the cases given the latest failure.
		// repairCases returns the same map when the LLM has nothing
		// better to suggest; we then break on `len(newCases)==0` so a
		// stuck LLM does not pin the loop.
		newCases, rerr := repairCases(ctx, file, opts.UseLLM, casesMap, out)
		if rerr != nil || len(newCases) == 0 {
			outputs = append(outputs, fmt.Sprintf("--- repair %d failed: %v ---", attempt, rerr))
			break
		}
		casesMap = newCases
	}

	return Result{
		GeneratedFiles: gen,
		TestOutput:     joinAttemptOutputs(outputs),
		TestPassed:     false,
		// Only set Error when LLM repair was attempted AND failed:
		// a plain go-test failure is reported via TestPassed==false
		// which is the conventional surface (no false alarms on the
		// single-pass path).
		Error: repairErrorIfLoop(opts.MaxRepairIters, len(outputs)),
	}
}

func generateForPackage(ctx context.Context, opts Options) Result {
	pkg := opts.Package
	if pkg == "" {
		pkg = "./..."
	}

	if hasGotests() {
		out, err := runGotestsPackage(ctx, pkg)
		if err != nil {
			return Result{Error: fmt.Sprintf("gotests package failed: %v\n%s", err, out)}
		}
		testOut, passed := runGoTest(ctx, pkg)
		return Result{
			GeneratedFiles: detectGeneratedFiles(pkg),
			TestOutput:     testOut,
			TestPassed:     passed,
		}
	}

	// Fallback: enumerate .go files and generate for each.
	files, err := findGoFiles(pkg)
	if err != nil {
		return Result{Error: fmt.Sprintf("find go files: %v", err)}
	}

	var generated []string
	for _, f := range files {
		res := generateForFile(ctx, Options{
			File:           f,
			UseLLM:         opts.UseLLM,
			Overwrite:      opts.Overwrite,
			Timeout:        opts.Timeout,
			Cases:          opts.Cases,
			MaxRepairIters: opts.MaxRepairIters,
		})
		if res.Error != "" {
			return res
		}
		generated = append(generated, res.GeneratedFiles...)
	}

	pkgDir := "./..."
	if pkg != "./..." {
		pkgDir = pkg
	}
	out, passed := runGoTest(ctx, pkgDir)

	return Result{
		GeneratedFiles: generated,
		TestOutput:     out,
		TestPassed:     passed,
	}
}
